### ISSUE TITLE
Azure Pipelines build error: Bash exited with code '1' 

### ISSUE THREAD

**Issue by TalbotG** [web-platform-tests/wpt#34760] opened 2022-07-08 21:58 UTC
@web-platform-tests/wpt-core-team , @foolip , @web-platform-tests/admins , @stephenmcgruer ,

What does this "Azure Pipelines Build #20220708.45 failed" error 
"
Error analysis
Install Safari Technology Preview (CmdLine)
Bash exited with code '1'.
"
mean? What am I supposed to do regarding such error?

I have now such errors in [PR34705](https://github.com/web-platform-tests/wpt/pull/34705/), [PR34708](https://github.com/web-platform-tests/wpt/pull/34708/) and [PR34724](https://github.com/web-platform-tests/wpt/pull/34724/)

Please help.

Gérard

Addendum:

Starting: Install Safari Technology Preview
=
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
+ ./wpt install --channel preview --download-only -d . --rename STP safari browser
INFO:install:Now installing safari browser...
INFO:install:Finding STP download URLs
WARNING:install:Did not find any STP URLs
Traceback (most recent call last):
  File "/Users/runner/work/1/s/./wpt", line 10, in <module>
    wpt.main()
  File "/Users/runner/work/1/s/tools/wpt/wpt.py", line 220, in main
    rv = script(*args, **kwargs)
  File "/Users/runner/work/1/s/tools/wpt/install.py", line 89, in run
    install(browser, kwargs["component"], destination, channel, logger=logger,
  File "/Users/runner/work/1/s/tools/wpt/install.py", line 109, in install
    path = getattr(browser_cls(logger), method)(dest=destination, channel=channel, **kwargs)
  File "/Users/runner/work/1/s/tools/wpt/browser.py", line 1606, in download
    image_path = self._download_image(stp_downloads, tmpdir, system_version)
  File "/Users/runner/work/1/s/tools/wpt/browser.py", line 1524, in _download_image
    raise ValueError(f"no download for {system_version}")
ValueError: no download for 12.4
**##[error]Bash exited with code '1'.**

    Finishing: Install Safari Technology Preview

**Comment by whimboo** [comment] 2022-07-11 07:36
Dupe of #34752.

**Closed by whimboo** 2022-07-11 07:36 UTC
Labels: help wanted, help, GitHub Actions

**Comment by TalbotG** [comment] 2022-07-11 11:33
@whimboo Thank you, Henrik, for finding the duplicate of my issue.
