### ISSUE TITLE
./wpt serve fails with Python 3.12 (default on fedora39)

### ISSUE THREAD

**Issue by jschwe** [web-platform-tests/wpt#44578] opened 2024-02-14 09:39 UTC
Hi,

I've followed the description  on [how to setup a Linux system](https://web-platform-tests.org/running-tests/from-local-system.html#hosts-file-setup), and edited my hosts file by running `./wpt make-hosts-file | sudo tee -a /etc/hosts`, but `wpt serve` fails with an error telling me to update my hosts file:

<details><summary>./wpt serve</summary>
<p>

```
python3 ./wpt serve
[2024-02-14 10:29:08,023 None on port 35973] INFO - Starting http server on http://web-platform.test:35973
[2024-02-14 10:29:09,554 None on port 35973] INFO - Stopped http server on web-platform.test:35973
[2024-02-14 10:29:09,833 http on port 58649] INFO - Starting http server on http://web-platform.test:58649
[2024-02-14 10:29:09,836 http on port 8000] INFO - Starting http server on http://web-platform.test:8000
[2024-02-14 10:29:09,838 http-public on port 51541] INFO - Starting http server on http://web-platform.test:51541
[2024-02-14 10:29:09,841 http-private on port 60983] INFO - Starting http server on http://web-platform.test:60983
[2024-02-14 10:29:09,841 https on port 8443] INFO - Starting https server on https://web-platform.test:8443
[2024-02-14 10:29:09,842 https on port 8444] INFO - Starting https server on https://web-platform.test:8444
[2024-02-14 10:29:09,843 https-private on port 49609] INFO - Starting https server on https://web-platform.test:49609
[2024-02-14 10:29:09,843 https-public on port 45135] INFO - Starting https server on https://web-platform.test:45135
[2024-02-14 10:29:09,848 h2 on port 9000] INFO - Starting http2 server on https://web-platform.test:9000
[2024-02-14 10:29:10,142 ws on port 39591] INFO - Create socket on: (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 39591))
[2024-02-14 10:29:10,143 ws on port 39591] INFO - Bind on: (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 39591))
[2024-02-14 10:29:10,143 ws on port 39591] INFO - Listen on: (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 39591))
[2024-02-14 10:29:10,143 wss on port 47745] INFO - Create socket on: (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 47745))
[2024-02-14 10:29:10,144 wss on port 47745] CRITICAL - Please ensure all the necessary WPT subdomains are mapped to a loopback device in /etc/hosts.
See https://web-platform-tests.org/running-tests/from-local-system.html#system-setup for instructions.
INFO:root:Status of subprocess "http on port 8000": running
INFO:root:Status of subprocess "http on port 58649": running
INFO:root:Status of subprocess "http-private on port 60983": running
INFO:root:Status of subprocess "http-public on port 51541": running
INFO:root:Status of subprocess "https on port 8443": running
INFO:root:Status of subprocess "https on port 8444": running
INFO:root:Status of subprocess "https-private on port 49609": running
INFO:root:Status of subprocess "https-public on port 45135": running
INFO:root:Status of subprocess "ws on port 39591": running
INFO:root:Status of subprocess "wss on port 47745": running
INFO:root:Status of subprocess "h2 on port 9000": running
[2024-02-14 10:29:18,843 http on port 58649] INFO - Stopped http server on web-platform.test:58649
[2024-02-14 10:29:18,846 http on port 8000] INFO - Stopped http server on web-platform.test:8000
[2024-02-14 10:29:18,847 http-public on port 51541] INFO - Stopped http server on web-platform.test:51541
[2024-02-14 10:29:18,850 http-private on port 60983] INFO - Stopped http server on web-platform.test:60983
[2024-02-14 10:29:18,850 https on port 8443] INFO - Stopped http server on web-platform.test:8443
[2024-02-14 10:29:18,851 https on port 8444] INFO - Stopped http server on web-platform.test:8444
[2024-02-14 10:29:18,852 https-private on port 49609] INFO - Stopped http server on web-platform.test:49609
[2024-02-14 10:29:18,852 https-public on port 45135] INFO - Stopped http server on web-platform.test:45135
[2024-02-14 10:29:18,858 h2 on port 9000] INFO - Stopped http server on web-platform.test:9000
INFO:root:Status of subprocess "http on port 8000": exited correctly
INFO:root:Status of subprocess "http on port 58649": exited correctly
INFO:root:Status of subprocess "http-private on port 60983": exited correctly
INFO:root:Status of subprocess "http-public on port 51541": exited correctly
INFO:root:Status of subprocess "https on port 8443": exited correctly
INFO:root:Status of subprocess "https on port 8444": exited correctly
INFO:root:Status of subprocess "https-private on port 49609": exited correctly
INFO:root:Status of subprocess "https-public on port 45135": exited correctly
[2024-02-14 10:29:19,152 ws on port 39591] INFO - Close on: (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 39591))
INFO:root:Status of subprocess "ws on port 39591": exited correctly
WARNING:root:Status of subprocess "wss on port 47745": failed. Exit with non-zero status: 1
INFO:root:Status of subprocess "h2 on port 9000": exited correctly
```

</p>
</details>

<details><summary>/etc/hosts</summary>
<p>

```
❯ cat /etc/hosts
# Loopback entries; do not change.
# For historical reasons, localhost precedes localhost.localdomain:
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
# See hosts(5) for proper format and other examples:
# 192.168.1.10 foo.mydomain.org foo
# 192.168.1.13 bar.mydomain.org bar

127.0.0.1	www2.www2.not-web-platform.test
127.0.0.1	xn--lve-6lad.not-web-platform.test
127.0.0.1	www2.www.web-platform.test
127.0.0.1	xn--lve-6lad.web-platform.test
127.0.0.1	www.www2.not-web-platform.test
127.0.0.1	xn--n8j6ds53lwwkrqhv28a.xn--n8j6ds53lwwkrqhv28a.not-web-platform.test
127.0.0.1	xn--lve-6lad.xn--lve-6lad.web-platform.test
127.0.0.1	www1.www1.not-web-platform.test
127.0.0.1	www.www1.web-platform.test
127.0.0.1	www1.www2.web-platform.test
127.0.0.1	xn--lve-6lad.xn--n8j6ds53lwwkrqhv28a.not-web-platform.test
127.0.0.1	www2.www1.not-web-platform.test
127.0.0.1	www2.xn--n8j6ds53lwwkrqhv28a.web-platform.test
127.0.0.1	www2.www.not-web-platform.test
127.0.0.1	www.www.not-web-platform.test
127.0.0.1	xn--n8j6ds53lwwkrqhv28a.www2.web-platform.test
127.0.0.1	xn--n8j6ds53lwwkrqhv28a.www.web-platform.test
127.0.0.1	www2.www2.web-platform.test
127.0.0.1	xn--n8j6ds53lwwkrqhv28a.web-platform.test
127.0.0.1	xn--lve-6lad.www.web-platform.test
127.0.0.1	www2.xn--lve-6lad.web-platform.test
127.0.0.1	xn--n8j6ds53lwwkrqhv28a.www2.not-web-platform.test
127.0.0.1	xn--lve-6lad.xn--n8j6ds53lwwkrqhv28a.web-platform.test
127.0.0.1	www.xn--n8j6ds53lwwkrqhv28a.web-platform.test
127.0.0.1	www1.xn--lve-6lad.web-platform.test
127.0.0.1	www1.www2.not-web-platform.test
127.0.0.1	xn--lve-6lad.www1.not-web-platform.test
127.0.0.1	www.not-web-platform.test
127.0.0.1	www1.www.not-web-platform.test
127.0.0.1	www1.xn--lve-6lad.not-web-platform.test
127.0.0.1	www1.web-platform.test
127.0.0.1	www2.web-platform.test
127.0.0.1	www2.xn--n8j6ds53lwwkrqhv28a.not-web-platform.test
127.0.0.1	xn--n8j6ds53lwwkrqhv28a.www1.web-platform.test
127.0.0.1	www.xn--lve-6lad.not-web-platform.test
127.0.0.1	xn--lve-6lad.www2.not-web-platform.test
127.0.0.1	www.www2.web-platform.test
127.0.0.1	xn--n8j6ds53lwwkrqhv28a.not-web-platform.test
127.0.0.1	xn--n8j6ds53lwwkrqhv28a.www.not-web-platform.test
127.0.0.1	www1.xn--n8j6ds53lwwkrqhv28a.web-platform.test
127.0.0.1	web-platform.test
127.0.0.1	www.xn--lve-6lad.web-platform.test
127.0.0.1	www.xn--n8j6ds53lwwkrqhv28a.not-web-platform.test
127.0.0.1	www2.www1.web-platform.test
127.0.0.1	xn--lve-6lad.xn--lve-6lad.not-web-platform.test
127.0.0.1	xn--n8j6ds53lwwkrqhv28a.xn--n8j6ds53lwwkrqhv28a.web-platform.test
127.0.0.1	www1.www1.web-platform.test
127.0.0.1	xn--lve-6lad.www1.web-platform.test
127.0.0.1	xn--n8j6ds53lwwkrqhv28a.xn--lve-6lad.not-web-platform.test
127.0.0.1	xn--lve-6lad.www.not-web-platform.test
127.0.0.1	www1.xn--n8j6ds53lwwkrqhv28a.not-web-platform.test
127.0.0.1	not-web-platform.test
127.0.0.1	www2.not-web-platform.test
127.0.0.1	xn--n8j6ds53lwwkrqhv28a.xn--lve-6lad.web-platform.test
127.0.0.1	www.www1.not-web-platform.test
127.0.0.1	xn--lve-6lad.www2.web-platform.test
127.0.0.1	www.www.web-platform.test
127.0.0.1	www1.www.web-platform.test
127.0.0.1	www2.xn--lve-6lad.not-web-platform.test
127.0.0.1	www.web-platform.test
127.0.0.1	www1.not-web-platform.test
127.0.0.1	xn--n8j6ds53lwwkrqhv28a.www1.not-web-platform.test


```

</p>
</details>

Python version: `Python 3.12.1`
Python (without 3) is also available: 
```
python --version
Python 3.12.1
```
Any tips or hints on how to resolve this error?

**Comment by jschwe** [comment] 2024-02-15 08:59
I've resolved this locally by running `wpt` in a venv with Python 3.11.

**Comment by gsnedders** [comment] 2024-02-15 19:37
Effectively a duplicate of #44427.

**Closed by gsnedders** 2024-02-15 19:37 UTC
