### ISSUE TITLE
wptserve raises exceptions when serving serviceworker tests generated from `.https.any.js`

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt#12301] opened 2018-08-03 18:31 UTC
Example: [`payment-handler/idlharness.https.any.js`](https://github.com/web-platform-tests/wpt/blob/master/payment-handler/idlharness.https.any.js) (in particular, the automatically generated variant `/payment-handler/idlharness.https.any.serviceworker.html`).

```
Traceback (most recent call last):
  File "/usr/local/google/home/robertma/github/wpt/tools/wptserve/wptserve/handlers.py", line 264, in __call__
    rv = self.func(request, response)
  File "/usr/local/google/home/robertma/github/wpt/tools/serve/serve.py", line 61, in handle_request
    self.check_exposure(request)
  File "/usr/local/google/home/robertma/github/wpt/tools/serve/serve.py", line 161, in check_exposure
    for (key, value) in self._get_metadata(request):
  File "/usr/local/google/home/robertma/github/wpt/tools/serve/serve.py", line 103, in _get_metadata
    with open(path, "rb") as f:
IOError: [Errno 2] No such file or directory: '/usr/local/google/home/robertma/github/wpt/payment-handler/idlharness.any.js'
```

Looks like something wrong in `wpt serve` (namely `path_replace`):
https://github.com/web-platform-tests/wpt/blob/e2ecba285ca6a9e7c885ab930fb0eca6a7d00499/tools/serve/serve.py#L72

It tries to serve `foo.any.js` for `foo.https.any.serviceworker.html`, but in this case only `foo.https.any.js` exists. This path replacing logic doesn't seem obvious to me so I don't know how to fix it properly off the top of my head.

**Comment by Hexcles** [comment] 2018-08-03 18:32
cc @Ms2ger who recently touched the related code.

**Comment by foolip** [comment] 2018-08-04 21:00
`find . -name *.https.any.js | wc -l` says that 40 tests are affected.

**Comment by foolip** [comment] 2018-08-04 21:06
@jgraham, is this the same problem as https://github.com/web-platform-tests/wpt/pull/11151 is fixing?

I was going to bisect, but going back I couldn't any .https.any.js test with global=worker where problem wasn't present.

**Comment by gsnedders** [comment] 2018-08-09 13:03
@foolip looks like it, yes

**Comment by gsnedders** [comment] 2018-08-09 15:21
Dupe of #11105.

**Closed by gsnedders** 2018-08-09 15:21 UTC
Labels: infra, priority:urgent
