### ISSUE TITLE
Missing safari stable runs on wpt.fyi - unable to locate safaridriver

### ISSUE THREAD

**Issue by LukeZielinski** [web-platform-tests/wpt#24784] opened 2020-07-28 15:25 UTC
Last successful run was on July 19, so over a week of missing runs.

Here is an example of the error: https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=51813&view=logs&j=9f79e71d-035e-5d82-255d-685df306f83d&t=b21de8b3-fd08-5869-a849-131ec765500e

Stack trace copied for convenience:
```
Traceback (most recent call last):
  File "./wpt", line 21, in <module>
    wpt.main()
  File "/Users/runner/work/1/s/tools/wpt/wpt.py", line 171, in main
    rv = script(*args, **kwargs)
  File "/Users/runner/work/1/s/tools/wpt/run.py", line 818, in run
    wptrunner_kwargs = setup_wptrunner(venv, **kwargs)
  File "/Users/runner/work/1/s/tools/wpt/run.py", line 786, in setup_wptrunner
    setup_cls.setup(kwargs)
  File "/Users/runner/work/1/s/tools/wpt/run.py", line 177, in setup
    self.setup_kwargs(kwargs)
  File "/Users/runner/work/1/s/tools/wpt/run.py", line 595, in setup_kwargs
    raise WptrunError("Unable to locate safaridriver binary")
tools.wpt.run.WptrunError: Unable to locate safaridriver binary
```

**Comment by stephenmcgruer** [comment] 2020-07-28 15:26
Last good run was on the 19th. On the 20th, https://github.com/web-platform-tests/wpt/pull/24651 landed - @Hexcles do you think that could be related?

**Comment by stephenmcgruer** [comment] 2020-07-28 15:27
cc @gsnedders as an FYI

**Comment by stephenmcgruer** [comment] 2020-07-28 15:55
So `.azurepipelines.yml` for stable doesn't specify `--channel=stable`. Which means it should get the default, which should always have been nightly. For some reason, that previously didn't work and it was getting the stable channel. After @Hexcles refactoring, it now 'works', which breaks Safari stable.

I've sent a fix for this, but we should figure out what changed as well cause that's really scary.

**Comment by gsnedders** [comment] 2020-07-28 21:55
Why shouldn't it have worked? Historically we did default to the stable release (because it was most likely to be installed), and we often didn't pay attention to the channel unless we needed to (which with Safari having differing binaries for everything, and safaridriver shipping with it there was no need to).

**Comment by stephenmcgruer** [comment] 2020-07-28 22:00
> Historically we did default to the stable release

That's not what the code said? https://github.com/web-platform-tests/wpt/pull/24651/commits/3a94bf2b9a3b138cb81efb9470e5eb06e5e1dea3 moved the code, but the default value for `channel` was already `nightly`. The code before that was added in 41d8548ced361d2f40996cc5ad27f06bc9e56da7, which seems to imply that nightly-by-default was the intended behavior?

**Comment by Hexcles** [comment] 2020-07-28 22:01
I might have misunderstood the original intention (which was arguably a bit confusing) in my #24651 then.

Looks like both `wpt install` and `wpt run --install-browser` have always defaulted to `--channel=nightly`, but `wpt run` (without `--install-browser`) itself did not really have a global default but defaults to nightly for at least Chrome and Firefox.

**Comment by gsnedders** [comment] 2020-07-29 20:03
FWIW, I think being consistent is good, but we should also give the user guidance in the case we can't install anything ourselves.

**Comment by Hexcles** [comment] 2020-07-29 20:05
That's a good point. On that note, @stephenmcgruer was surprised about another channel aliasing today. We do have `logger.info` for "interpreting ... as ...", but it's hidden by default. We'd have to raise it all the way to `logger.error` to show it by default, which is probably wrong semantically.

**Comment by stephenmcgruer** [comment] 2020-08-01 11:40
I believe Safari runs are happening now, so I'm dropping this to roadmap. I still want to briefly (locally) revert the refactor PR and see why it previously picked stable, but after that will close this.

**Comment by gsnedders** [comment] 2020-08-11 17:47
@stephenmcgruer can you change the title of the issue if it's not true now?

**Comment by stephenmcgruer** [comment] 2020-08-11 17:58
I'm just going to close it fixed instead :). Me doing a code spelunk to figure out the previous reason doesn't require this to be open.

**Closed by stephenmcgruer** 2020-08-11 17:58 UTC
Labels: infra, priority:roadmap
