### ISSUE TITLE
[css-writing-modes-3] bidi-002 has a slight offset between "C" and "D" on Trident

### ISSUE THREAD

**Issue by wpt-issue-mover** [web-platform-tests/wpt#5461] opened 2017-04-07 14:11 UTC
Originally posted as https://github.com/w3c/csswg-test/issues/796 by @kojiishi on 09 Jul 2015, 07:06 UTC:

> [bidi-002](http://test.csswg.org/harness/test/css-writing-modes-3_dev/single/bidi-002/format/html5/)  has a slight offset between "C" and "D" on Trident. Is this a failure, or an issue in test?

**Comment by frivoal** [comment] 2018-01-28 13:22
Interesting. Edge might actually be correct here. Going by CSS-Text-3, I believe the following should happen:
> If white-space is set to normal, nowrap, or pre-line, white space characters are considered collapsible and are processed by performing the following steps:
> 
> 1.   All spaces and tabs immediately preceding or following a segment break are removed. 

Therefore, the spaces at the beginning of line 37 (before LLL) are removed
> 2. Segment breaks are transformed for rendering according to the segment break transformation rules. 

These rules are there: https://drafts.csswg.org/css-text-3/#line-break-transform
and following them, the segment break at the end of line 36 is converted to a space (U+0020). 

> Then, the entire block is rendered. Inlines are laid out, taking bidi reordering into account, 

That space ends up in the middle of the line, visually between CCC and DDD.

Then [4.1.3. Phase II: Trimming and Positioning](https://drafts.csswg.org/css-text-3/#white-space-phase-2) calls for removing spaces at the end of a line, but bidi reordering has already happened, and that space isn't visually at the end, so I don't think there's anything that justifies getting rid of it.

To me, it looks like browsers other than edge do "4.1.3. Phase II: Trimming and Positioning"  before bidi reordering, but that's not what CSS-Text-3 calls for as far as I can tell.

Or did I get that wrong? @fantasai , what's your take on this?

**Comment by frivoal** [comment] 2018-01-28 13:25
Note: either way, regardless of whether the bug is in Edge/other browsers/the spec, it's a CSS2 / CSS-Text-3 bug, What's in scope for CSS-Writing-modes (bidi reordering itself) is working as intended.

**Comment by fantasai** [comment] 2018-01-29 23:01
Test seems to be passing on Firefox 58 for Linux. Maybe there's some kind of font kerning issue?

**Comment by fantasai** [comment] 2018-01-30 01:58
I guess the key question is: if we set the test to use Ahem (which should not be pushed to WPT since it can't represent bidi reordering) or the Last Resort font, does it still fail? If so, it's a layout bug. If not, it's probably some complication of font rendering across bidi boundaries.

**Comment by frivoal** [comment] 2018-01-31 02:35
The test does pass in Firefox (and Chrome, and Safari). It doesn't pass in Edge, but I'm thinking Edge may be correct, while the test (and other browsers that pass it) are wrong.

It is not a kerning issue, Edge clearly preserves a space where other browsers do not: at the end (i.e. left after bidi reordering) of the logical `FFFEEEDDD` / visual `DDDEEEFFF` run.

As far as I can tell (see details in https://github.com/w3c/web-platform-tests/issues/5461#issuecomment-361062673), css-text-3 says to do bidi reordering first, and suppression of white space at the end of line later, and to me it means that Edge is doing the correct thing.

**Comment by frivoal** [comment] 2019-08-19 17:21
@fantasai ping?

**Comment by frivoal** [comment] 2020-02-10 05:04
Closing, as #4308 clarified that the Firefox/Chrome behavior, which is the one expected by the test, is the expected one.

**Closed by frivoal** 2020-02-10 05:04 UTC
Labels: CSS2, css-text, css-writing-modes, wg-css
