### ISSUE TITLE
Feb 5 WebKitGTK run failed

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#21594] opened 2020-02-05 12:28 UTC
https://community-tc.services.mozilla.com/tasks/groups/FNdOcyadTe-Up-H0DH0Dbw for commit e3f453715b7945000cf4a02727fa2fb0f6563e7a failed in the wpt-webkitgtk_minibrowser-nightly-testharness-16 task.

The first sign of trouble in the logs is this:
```
CRITICAL Traceback (most recent call last):
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 126, in run_test
    return self.executor.run_test(test)
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/executors/base.py", line 255, in run_test
    self.on_environment_change(test.environment)
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 361, in on_environment_change
    self.protocol.testharness.load_runner(new_environment["protocol"])
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 94, in load_runner
    self.webdriver.url = url
  File "/home/test/web-platform-tests/tools/webdriver/webdriver/client.py", line 19, in inner
    return func(self, *args, **kwargs)
  File "/home/test/web-platform-tests/tools/webdriver/webdriver/client.py", line 528, in url
    return self.send_session_command("POST", "url", body)
  File "/home/test/web-platform-tests/tools/webdriver/webdriver/client.py", line 515, in send_session_command
    return self.send_command(method, url, body)
  File "/home/test/web-platform-tests/tools/webdriver/webdriver/client.py", line 470, in send_command
    session=self)
  File "/home/test/web-platform-tests/tools/webdriver/webdriver/transport.py", line 175, in send
    response = self._request(method, uri, payload, headers)
  File "/home/test/web-platform-tests/tools/webdriver/webdriver/transport.py", line 191, in _request
    return self.connection.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1137, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 448, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 412, in _read_status
    raise BadStatusLine("No status line received - the server has closed the connection")
BadStatusLine: No status line received - the server has closed the connection
```

It looks like the webdriver server has died or become unresponsive and the restart logic isn't working.

**Comment by clopez** [comment] 2020-02-05 13:26
This happened also on Jan-7 and Dec-25 with the very same backtrace. See #20902
So far I was unable to reproduce locally. What I would try next is to try to force that error condition (webdriver unresponsive) and try to improve the WPT logic to restart it instead of failing the run.

**Comment by clopez** [comment] 2020-02-06 21:37
If you take a careful look at what happened on the run you see that the test step completed.
```
35:08.72 INFO No more tests
35:08.80 INFO Closing logging queue
35:08.80 INFO queue closed
35:08.80 INFO Got 6745 unexpected results
35:08.80 SUITE_END

web-platform-test
~~~~~~~~~~~~~~~~~
Ran 464569 checks (462574 subtests, 1995 tests)
Expected results: 457809
Skipped: 15 tests
Unexpected results: 6745
  test: 76 (36 error, 40 timeout)
  subtest: 6669 (6527 fail, 96 notrun, 3 precondition_failed, 43 timeout)
```

That its where the step ends. But after that the match logger proceeds to log all errors it got during the run. So the output its a bit confusing and it looks like it aborts when the traceback is logged, but it doesn't do that. It recovers correctly from the traceback restarting webdriver and continues. You can verify that by looking for that traceback above (above the line `SUITE_END`)

So why it ends the step with non-zero status?
Just because it has used logger.critical to log the traceback when it restarted.
You can reproduce that with this patch:

```patch
--- a/tools/wptrunner/wptrunner/testrunner.py
+++ b/tools/wptrunner/wptrunner/testrunner.py
@@ -499,7 +499,7 @@ class TestRunnerManager(threading.Thread):
         assert isinstance(self.state, RunnerManagerState.initializing)
         assert self.command_queue is not None
         assert self.remote_queue is not None
-        self.logger.info("Starting runner")
+        self.logger.critical("Starting runner")
         executor_browser_cls, executor_browser_kwargs = self.browser.browser.executor_browser()
 
         args = (self.remote_queue,
```

The simple fact of logging that with critical instead of info will make wpt run return non-zero status.

So I think that to fix this we need to user logger.error instead of critical for logging the traceback.

**Comment by clopez** [comment] 2020-02-11 17:06
Hopefully this should not happen again after 439244b257
Closing this. Please reopen if it happens again.

**Closed by clopez** 2020-02-11 17:06 UTC
Labels: infra, priority:roadmap
