### ISSUE TITLE
`infrastructure/` tests can silently break

### ISSUE THREAD

**Issue by jonathan-j-lee** [web-platform-tests/wpt#37092] opened 2022-11-22 21:08 UTC
`infrastructure/` runs against nightly builds of each browser (i.e., are not pinned to a version). As browsers regress or receive bug fixes, the expectations stored under [`infrastructure/metadata/`](https://github.com/web-platform-tests/wpt/tree/master/infrastructure/metadata) can become stale. This can cause unexpected results on the next CI run and block unrelated changes.

Examples:
* #37038
* #36504
* #35975

cc @WeizhongX

**Comment by jgraham** [comment] 2022-12-22 11:42
I don't have a proposal for something better here. The obvious alternative would be building out infrastructure to allow pinning to specific versions of browsers and then creating PRs to update the browser version. But my guess is whilst that's going to look more professional ("other infra PRs less likely to be blocked on browser issues"), it's actually going to be more work overall to build the infrastructure and approve the updates. On the other hand if you have the bandwidth to do the work, and a way to make the updates almost seamless, then I don't object. I just wouldn't prioritise it myself.

**Comment by foolip** [comment] 2022-12-22 16:24
This is a dupe of https://github.com/web-platform-tests/wpt/issues/14456, closing and commenting there.

**Closed by foolip** 2022-12-22 16:24 UTC
Labels: infra
