### ISSUE TITLE
Programmatically making time elapse

### ISSUE THREAD

**Issue by mfalken** [web-platform-tests/wpt#27324] opened 2021-01-26 08:15 UTC
While triaging WPT failures, I discovered service-workers/service-worker/update-after-oneday.https.html.

This test requires a special preference:
` `

This was previously discussed here: https://github.com/web-platform-tests/wpt/issues/16455#issuecomment-532507904

More generally, it may be useful to have WPT infra to make time elapse inside of a test.

**Comment by stephenmcgruer** [comment] 2021-01-26 12:16
Duplicate of https://github.com/web-platform-tests/wpt/issues/17489, I believe. Please re-open if I'm wrong.

**Closed by stephenmcgruer** 2021-01-26 12:16 UTC
Labels: duplicate, type:untestable
