### ISSUE TITLE
@pytest.mark.parametrize handles escape characters differently for Python2 and Python 3

### ISSUE THREAD

**Issue by ziransun** [web-platform-tests/wpt#24888] opened 2020-08-05 12:51 UTC
When calling `@pytest.mark.parametrize` in tests, if argument contains escape characters (e.g. `\n`, `\t `etc.), it produces different test names in PY2 and PY3.

Examples:
```
@pytest.mark.parametrize("text", [..., "Fed\terer"] produces test names 
test_send_alert_text[Fed erer] for PY2
test_send_alert_text[Fed\terer] for PY3
```

_https://wpt.fyi/results/webdriver/tests/send_alert_text/send.py?diff&filter=ADC&run_id=632440001&run_id=619000003
https://wpt.fyi/results/webdriver/tests/find_element/find.py?diff&filter=ADC&run_id=632440001&run_id=619000003_

This is very likely due to that in PY2 the default type for strings was str, but it was stored as byte while in PY3 str corresponds to unicode type. Python string literals treat backslashes as initiating escape sequences (e.g.` \n` is LF). For unicode, it retains characters as it is (e.g. `'\n'` is `'\n`'). 

It is also noted that @pytest.mark.parametrize expects `str` type arguments.

**Comment by Hexcles** [comment] 2020-08-05 14:02
cc @jgraham could you take a look?

I think these test names are generated by pytest, so whatever escaping happens there. Is there anything we can do? Or would you (and other folks working on WebDriver) be fine with the change of test names? (To me, the PY3 representation seems more user-friendly.)

**Comment by gsnedders** [comment] 2020-08-05 23:18
I think this was a change in pytest after it went Python 3 only?

**Comment by jgraham** [comment] 2020-09-15 14:34
I'm not very worried by a small number of changes here.

**Comment by stephenmcgruer** [comment] 2020-09-15 14:34
Given that this is just a few (~10?) tests in `webdriver/`, and since the Py3 names are nicer than the Py2 names, I'm inclined to say this is WAI and accept the difference in test names until we're Py3-only (which is a long time away).

**Comment by stephenmcgruer** [comment] 2020-09-15 15:31
Yep; closing working as intended.

@ziransun - please note but ignore any diffs caused by this problem in your Py2/Py3 analysis work.

**Closed by stephenmcgruer** 2020-09-15 15:31 UTC
Labels: infra, priority:roadmap, python3, webdriver

**Comment by ziransun** [comment] 2020-09-16 08:16
> @ziransun - please note but ignore any diffs caused by this problem in your Py2/Py3 analysis work.

Updated the analysis worksheets.
