### ISSUE TITLE
Travis does not produce output 

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt#14064] opened 2018-11-14 23:19 UTC
https://travis-ci.org/web-platform-tests/wpt/jobs/455082483

Travis doesn't produce any output from the tests in the CL above. As a result, it blocks the export PRs queue. I suspect the process is hanging when running these tests from Travis.

If running it locally, it does show results and the process does not hang at all. Sample output looks like 

requests 2.19.1 has requirement urllib3<1.24,>=1.21.1, but you'll have urllib3 1.24.1 which is incompatible.
Running 1 tests in web-platform-tests

  ▶ Unexpected subtest result in /feature-policy/reporting/xr-report-only.https.html:
  │ FAIL [expected PASS] XR report only mode
  │   → assert_equals: expected "NotFoundError" but got "TypeError"
  │ 
  │     at Test.promise_test (https://web-platform.test:8443/feature-policy/reporting/xr-report-only.https.html:31:5)
  │     at Test.step (https://web-platform.test:8443/resources/testharness.js:1568:25)
  │     at https://web-platform.test:8443/resources/testharness.js:591:36
  │     at new Promise (<anonymous>)
  └     at https://web-platform.test:8443/resources/testharness.js:590:20

Ran 1 tests finished in 2.0 seconds.
  • 0 ran as expected. 0 tests skipped.
  • 1 tests had unexpected subtest results

requests 2.19.1 has requirement urllib3<1.24,>=1.21.1, but you'll have urllib3 1.24.1 which is incompatible.
Running 1 tests in web-platform-tests

  ▶ Unexpected subtest result in /feature-policy/reporting/xr-reporting.https.html:
  │ FAIL [expected PASS] XR Report Format
  │   → promise_test: Unhandled rejection with value: object "TypeError: Cannot read property 'requestDevice' of undefined"
  │ 
  │ Error
  │     at AssertionError.get_stack (https://web-platform.test:8443/resources/testharness.js:2983:21)
  │     at new AssertionError (https://web-platform.test:8443/resources/testharness.js:2976:27)
  │     at assert (https://web-platform.test:8443/resources/testharness.js:2969:19)
  │     at Test.<anonymous> (https://web-platform.test:8443/resources/testharness.js:617:29)
  │     at Test.step (https://web-platform.test:8443/resources/testharness.js:1568:25)
  └     at https://web-platform.test:8443/resources/testharness.js:1592:35

Ran 1 tests finished in 2.0 seconds.
  • 0 ran as expected. 0 tests skipped.
  • 1 tests had unexpected subtest results

**Comment by sideshowbarker** [comment] 2018-11-16 05:15
This seems like a duplicate of #7660. See also #14033. And #13984 (the PR affected by the Travis failures) has since been merged to master, so I’m gonna go ahead and close this issue.

**Closed by sideshowbarker** 2018-11-16 05:15 UTC
