### ISSUE TITLE
Payment Request tests not running on Safari Technology Preview

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#18635] opened 2019-08-23 11:11 UTC
https://github.com/web-platform-tests/wpt/pull/18585 disabled all of payment-request/ on Safari Technology Preview (but not stable) because they somehow interrupting the test run.

They should be enabled again when the root cause has been fixed.

@marcoscaceres @rsolomakhin @zouhir @romandev @aestes @danyao FYI

**Comment by rsolomakhin** [comment] 2019-08-23 13:41
The following tests errored-out on Safari technology preview:
```
  ▶ TIMEOUT [expected OK] /payment-method-basic-card/steps_for_selecting_the_payment_handler.html

  ▶ CRASH [expected OK] /payment-request/payment-is-showing.https.html

  ▶ TIMEOUT [expected OK] /payment-request/payment-request-show-method.https.html

##[section]Finishing: Run tests
```
@aestes : Are you able to reproduce these test failures locally on your machine?

**Comment by foolip** [comment] 2019-08-23 19:01
The crash is interesting, but timeouts probably aren't related to the root cause here.

I would guess the cause is actually the use of `test_driver.bless`, and that it might be fixed by https://github.com/web-platform-tests/wpt/issues/17186, so wouldn't recommend spending a lot of time debugging this now.

A quick look might be hold though :)

**Comment by aestes** [comment] 2019-10-14 21:23
I believe the crash @rsolomakhin observed in `/payment-request/payment-is-showing.https.html` is due to the same underlying bug that was interrupting the test run.

That was fixed in https://trac.webkit.org/r246345 and I'm able to run /payment-request/ tests to completion on https://www.w3c-test.org/tools/runner/ in the latest Safari Technology Preview (93).

**Comment by foolip** [comment] 2019-10-14 21:32
@aestes great, it sounds like there's hope of this being fixed with STP 94 then. See https://github.com/web-platform-tests/wpt/issues/17186 for why we're stuck on an old version of STP. (If anyone has successfully installed and run STP 93 in a public CI system, I'd love to know how.)

**Comment by foolip** [comment] 2019-10-18 08:07
Because of the mishap described in https://github.com/web-platform-tests/wpt/issues/19311#issuecomment-543584515 there's now a commit on master that I could use to trigger a run to see if the `--exclude` arguments are still needed:
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=34808

(I had meant to do that test from a branch.)

**Closed** 2019-10-18 15:39 UTC
Labels: payment-request
