### ISSUE TITLE
Critical TestManager errors should cause non-zero exit

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#13073] opened 2018-09-19 11:09 UTC
e.g. https://github.com/web-platform-tests/wpt/issues/12874 which exceeds max restarts should be a critical error which should then cause a non-zero exit (and a job failure on TC etc.), given we haven't actually run all tests requested.

**Comment by foolip** [comment] 2018-09-24 19:55
@jugglinmike, thoughts on the priority of this?

**Comment by jugglinmike** [comment] 2018-09-24 21:47
It's tough to say without an understanding of the frequency. [I posted some research on the original issue](https://github.com/web-platform-tests/wpt/issues/12874#issuecomment-424135171), and that suggests it will only effect contributors running tasks from their own forks of WPT.

If that's right, it reduces the priority for a fix, but we should still fix this. For one, [we explicitly support the "bring your own fork" use case](https://github.com/web-platform-tests/wpt/blob/b040cb2a07264d35b9f47cd9deb2fb2889fca6d4/.taskcluster.yml#L49-L54).  For another, it's possible that there are (or will be) other failures of this class that *do* effect WPT, and those would interfere with results collection (by creating incomplete result sets) and pull request validation (by allowing regressions to be merged).

**Comment by gsnedders** [comment] 2018-10-08 11:14
Once #13407 is fixed, maybe that should be CRITICAL too, given it implies we didn't actually complete running everything?

**Comment by foolip** [comment] 2018-10-29 11:00
https://github.com/web-platform-tests/wpt/issues/13747 has another instance of this, and in https://github.com/foolip/wpt/pull/7/checks?check_run_id=26935477 I've done some debugging. So far I see two options, not mutually exclusive:
* Ignore what the TestRunnerManager and TestRunner claims about total number of tests, instead check if we got results for (or explicitly skipped) every test we wanted to run.
* Propagate the "did exit cleanly" information outwards and fail if not everything exited cleanly. This is what I tinkered with in https://github.com/foolip/wpt/pull/7.

@gsnedders, can you take over fixing this, since it is already in [Q4 OKRs](https://docs.google.com/document/d/1UKuPaQm2YGHYEfbrrYBHoCUGAVhyQZEp8nE09qT7vYg/edit#heading=h.jwokykbtd9cq)?

**Comment by gsnedders** [comment] 2018-10-29 18:39
Basically I think we want to turn that error into a CRITICAL error, and exit with failure if there are any CRITICAL errors.

**Comment by foolip** [comment] 2018-10-29 20:24
Yeah, that would obviate the need to move information through multiple layers, and also would make sense.

**Comment by mdittmer** [comment] 2019-01-25 15:15
_friendly ping_. @gsnedders looks like there are requested changes on the proposed fix. Is driving forward #14604 still on your radar?

**Comment by gsnedders** [comment] 2019-01-28 14:46
@mdittmer Yes. Fundamentally the wrong approach, probably, but a reasonable starting point at exploring the space here.

**Comment by foolip** [comment] 2019-02-19 22:42
This caused incorrect passes on https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=7289.

**Comment by foolip** [comment] 2019-08-15 10:28
https://github.com/web-platform-tests/wpt/issues/18397 is another instance of this. @gsnedders I *think* this is the infra issue that's causing the most trouble, and would be most worthwhile getting fixed.

**Comment by foolip** [comment] 2019-08-21 11:53
Another flavor of this in https://github.com/web-platform-tests/wpt/pull/18585#issuecomment-523421624, where this happened:
```
TEST-START | /payment-request/payment-request-show-method.https.html
click <Element node-27642BA5-3D33-49E9-A4D1-133A990AC681>
click <Element node-6D3C4947-E9A6-40C1-8538-B838CC80717B>
click <Element node-A51F9118-7F65-4A86-808F-8C4D19F12E85>
click <Element node-8F078A1E-FD0C-4DB4-A446-E935F68E8207>
TEST-PASS | /payment-request/payment-request-show-method.https.html | Calling show() without being triggered by user interaction throws 
TEST-PASS | /payment-request/payment-request-show-method.https.html | Throws if the promise [[state]] is not 'created'. 
TEST-PASS | /payment-request/payment-request-show-method.https.html | If the user agent's "payment request is showing" boolean is true, then return a promise rejected with an "AbortError" DOMException. 
TEST-PASS | /payment-request/payment-request-show-method.https.html | If payment method consultation produces no supported method of payment, then return a promise rejected with a "NotSupportedError" DOMException. 
TEST-PASS | /payment-request/payment-request-show-method.https.html | Calling show() multiple times always returns a new promise. 
TEST-OK | /payment-request/payment-request-show-method.https.html | took 489ms
TEST-START | /performance-timeline/get-invalid-entries.html
Traceback (most recent call last):
  File "/Users/vsts/agent/2.155.1/work/1/s/tools/wptrunner/wptrunner/testrunner.py", line 126, in run_test
    return self.executor.run_test(test)
  File "/Users/vsts/agent/2.155.1/work/1/s/tools/wptrunner/wptrunner/executors/base.py", line 191, in run_test
    self.on_environment_change(test.environment)
  File "/Users/vsts/agent/2.155.1/work/1/s/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 329, in on_environment_change
    self.protocol.testharness.load_runner(new_environment["protocol"])
  File "/Users/vsts/agent/2.155.1/work/1/s/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 78, in load_runner
    self.webdriver.window_handle = self.runner_handle
  File "/Users/vsts/agent/2.155.1/work/1/s/tools/webdriver/webdriver/client.py", line 20, in inner
    return func(self, *args, **kwargs)
  File "/Users/vsts/agent/2.155.1/work/1/s/tools/webdriver/webdriver/client.py", line 562, in window_handle
    return self.send_session_command("POST", "window", body=body)
  File "/Users/vsts/agent/2.155.1/work/1/s/tools/webdriver/webdriver/client.py", line 516, in send_session_command
    return self.send_command(method, url, body)
  File "/Users/vsts/agent/2.155.1/work/1/s/tools/webdriver/webdriver/client.py", line 480, in send_command
    raise err
InvalidSessionIdException: invalid session id (404): 


Error running command run_test with arguments (<wptrunner.wpttest.TestharnessTest /performance-timeline/get-invalid-entries.html>,):
Traceback (most recent call last):
  File "/Users/vsts/agent/2.155.1/work/1/s/tools/wptrunner/wptrunner/testrunner.py", line 109, in run
    rv = commands[command](*args)
  File "/Users/vsts/agent/2.155.1/work/1/s/tools/wptrunner/wptrunner/testrunner.py", line 126, in run_test
    return self.executor.run_test(test)
  File "/Users/vsts/agent/2.155.1/work/1/s/tools/wptrunner/wptrunner/executors/base.py", line 191, in run_test
    self.on_environment_change(test.environment)
  File "/Users/vsts/agent/2.155.1/work/1/s/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 329, in on_environment_change
    self.protocol.testharness.load_runner(new_environment["protocol"])
  File "/Users/vsts/agent/2.155.1/work/1/s/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 78, in load_runner
    self.webdriver.window_handle = self.runner_handle
  File "/Users/vsts/agent/2.155.1/work/1/s/tools/webdriver/webdriver/client.py", line 20, in inner
    return func(self, *args, **kwargs)
  File "/Users/vsts/agent/2.155.1/work/1/s/tools/webdriver/webdriver/client.py", line 562, in window_handle
    return self.send_session_command("POST", "window", body=body)
  File "/Users/vsts/agent/2.155.1/work/1/s/tools/webdriver/webdriver/client.py", line 516, in send_session_command
    return self.send_command(method, url, body)
  File "/Users/vsts/agent/2.155.1/work/1/s/tools/webdriver/webdriver/client.py", line 480, in send_command
    raise err
InvalidSessionIdException: invalid session id (404): 


Traceback (most recent call last):
  File "/Users/vsts/agent/2.155.1/work/1/s/tools/wptrunner/wptrunner/testrunner.py", line 386, in run
    new_state = self.wait_event()
  File "/Users/vsts/agent/2.155.1/work/1/s/tools/wptrunner/wptrunner/testrunner.py", line 461, in wait_event
    return f(*data)
  File "/Users/vsts/agent/2.155.1/work/1/s/tools/wptrunner/wptrunner/testrunner.py", line 682, in error
    self.restart_runner()
  File "/Users/vsts/agent/2.155.1/work/1/s/tools/wptrunner/wptrunner/testrunner.py", line 673, in restart_runner
    assert isinstance(self.state, RunnerManagerState.restarting)
AssertionError

Closing logging queue
queue closed
STDERR: Exception in thread TestRunnerManager-3:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Users/vsts/agent/2.155.1/work/1/s/tools/wptrunner/wptrunner/testrunner.py", line 386, in run
    new_state = self.wait_event()
  File "/Users/vsts/agent/2.155.1/work/1/s/tools/wptrunner/wptrunner/testrunner.py", line 461, in wait_event
    return f(*data)
  File "/Users/vsts/agent/2.155.1/work/1/s/tools/wptrunner/wptrunner/testrunner.py", line 682, in error
    self.restart_runner()
  File "/Users/vsts/agent/2.155.1/work/1/s/tools/wptrunner/wptrunner/testrunner.py", line 673, in restart_runner
    assert isinstance(self.state, RunnerManagerState.restarting)
AssertionError
Got 37947 unexpected results
SUITE-END | took 5213s
Closing logging queue
queue closed
```

The exit code was still zero.

**Closed** 2019-09-05 15:37 UTC
Labels: infra, priority:roadmap, wptrunner
