### ISSUE TITLE
Make it possible to run all tests for a PR sometimes

### ISSUE THREAD

**Issue by LukeZielinski** [web-platform-tests/wpt#18755] opened 2019-08-29 18:46 UTC
Wondering if we can make it possible for WPT to run *all* tests on a PR conditionally (eg: based on the presence of a particular label, or some kind of special tag in a PR description).

So if we add a label called "force-all-tests" to a PR then we could run a check equivalent to the "Taskcluster (push)" check.

Currently, this can be done by hacking .taskcluster.yml on a local fork and then doing some more hacking to manually upload the results to wpt.fyi. But this is highly brittle and error prone, would be nice if we could choose to run all tests when needed by a particular change.

**Comment by LukeZielinski** [comment] 2019-08-29 18:47
@lukebjerring @Hexcles @jgraham @foolip WDYT?

**Comment by lukebjerring** [comment] 2019-08-29 18:50
Also @jugglinmike definitely does this on occasion hackily.

**Comment by jugglinmike** [comment] 2019-08-29 18:53
The way I do this is sensitive and graceful

**Comment by foolip** [comment] 2019-08-29 18:58
I agree we need this, I've even requested it before :)

Closing as dupe of https://github.com/web-platform-tests/wpt/issues/13263, please suggest how to do it there :)

**Closed by foolip** 2019-08-29 18:58 UTC
