### ISSUE TITLE
Firefox is run with some feature flags turned on

### ISSUE THREAD

**Issue by koddsson** [web-platform-tests/wpt#23136] opened 2020-04-21 10:23 UTC
I've been working on preloading some scripts with the `Link` header and soon discovered that this feature is implemented behind a feature flag in Firefox.

[The WPT results for link preload however states that the test is passing in Firefox 75](https://wpt.fyi/results/preload/link-header-preload.html?label=master&label=stable&aligned). If you open up the [`wpt.live` site for that result](https://wpt.live/preload/link-header-preload.html) in Firefox 75 you'll see it failing though. This is because the `network.preload` Firefox preference is set to it's default, `false`. 

After some digging, I found that the feature flag is set to `true` [here](https://dxr.mozilla.org/mozilla-central/source/testing/profiles/web-platform/user.js#15-16) for Web Platform Tests.

This feels like some sort of oversight to me since I expected the tests to show me the test results from browsers as users use them in the wild with no feature flag enabled.

There might be a good reason for this that I'm not aware of but would it make sense to run Firefox without feature flags in order to accurately represent the browser as it is run by a majority of users?

### References

[Firefox tracking issue for `rel=preload`](https://bugzilla.mozilla.org/show_bug.cgi?id=1583604)

**Comment by guest271314** [comment] 2020-04-21 14:04
See https://github.com/web-platform-tests/wpt.fyi/issues/1648

**Comment by stephenmcgruer** [comment] 2020-04-21 14:11
I'm going to tentatively close this as a dupe of https://github.com/web-platform-tests/wpt/issues/20284; I agree it is concerning that Firefox stable is running with flags on that aren't turned on for an average user.

**Closed** 2020-04-21 14:11 UTC
Labels: duplicate

**Comment by koddsson** [comment] 2020-04-21 14:19
Thanks! I didn't find that issue previously 🙏🏻
