### ISSUE TITLE
Azure Pipelines checks have been failing

### ISSUE THREAD

**Issue by rakuco** [web-platform-tests/wpt#17118] opened 2019-05-31 16:35 UTC
See e.g. https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=17805&view=results from #17084 -- most Azure Pipeline checks today have been failing with an error that looks like

```
/tools/ci/azure/affected_tests.yml: Could not find /tools/ci/azure/update_hosts.yml in repository self hosted on https://api.github.com using commit 9d2c61d944a30d56c2e4715e79aa0a9cc1f3a0e0. GitHub reported the error, "Not Found"
```

with the file in `/tools/ci/azure/` that fails to be found changing randomly.

**Comment by rakuco** [comment] 2019-05-31 16:36
@foolip @Hexcles et al

**Comment by gsnedders** [comment] 2019-05-31 19:44
This is AFAIK a GitHub/Azure issue.

Note, however, the Azure jobs are not blocking (partly due to occasional unreliability like this) and in general PRs can be merged with them failing.

**Comment by foolip** [comment] 2019-06-03 09:32
@mustjab are you able pass along this failure to someone on the Azure Pipelines team? Would it help if we collect statistics and lists of failures, or can you easily get those internally too?

**Comment by foolip** [comment] 2019-06-04 13:10
In https://github.com/web-platform-tests/wpt/pull/16720/checks?check_run_id=141447864 I saw another type of failure. Seems like things are a little bit on fire between Azure and GitHub?

**Comment by foolip** [comment] 2019-06-10 12:30
Assigned to self to check in on this issue in a few months to see if it's still a problem.

**Comment by foolip** [comment] 2019-09-25 19:59
I'll close this as a dupe of https://github.com/web-platform-tests/wpt/issues/14763. Investigating old failure modes isn't very useful, understanding the current state and addressing what's currently causing failures is more useful.

**Closed by foolip** 2019-09-25 20:00 UTC
Labels: Azure Pipelines, infra, priority:roadmap
