### ISSUE TITLE
Improve coverage of JSON clone

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#31447] opened 2021-10-29 21:09 UTC
https://w3c.github.io/webdriver/#dfn-json-clone

Currently this has pretty poor coverage, though was slightly improved by https://github.com/web-platform-tests/wpt/pull/29877

We should have tests for attempting to return all DOM node types, along with some common interface instances.

We should also have tests for all of these where the object belongs to a different realm (e.g., from an iframe).

**Comment by whimboo** [comment] 2021-11-04 09:58
@gsnedders isn't that a dupe of #30157?

**Closed** 2021-11-09 03:19 UTC
Labels: webdriver, type:missing-coverage
