### ISSUE TITLE
Add automation API for WebDriver actions

### ISSUE THREAD

**Issue by kereliuk** [web-platform-tests/wpt#8152] opened 2017-11-10 20:36 UTC
Ref: #8151

**Comment by kereliuk** [comment] 2018-02-14 18:46
Yep, I am working on something that this is part of currently and plan to be finished before the end of the quarter.

**Comment by alijuma** [comment] 2018-04-20 15:09
Should this still be priority:roadmap?

**Comment by foolip** [comment] 2018-07-12 22:04
@kereliuk, this came up in priority:roadmap triage again today. Is this what you mentioned this week you've begun to work on?

**Comment by kereliuk** [comment] 2018-07-16 13:10
#11931 is a PR for the non-protocol specific portions (will unblock testdriver-vendor workflows).

**Comment by foolip** [comment] 2018-08-09 15:11
This is a dupe of https://github.com/web-platform-tests/wpt/issues/7435.

**Closed** 2018-08-09 15:12 UTC
Labels: infra, priority:roadmap, testdriver.js
