### ISSUE TITLE
PR25825 and "Bash exited with code '22'" CI failure message

### ISSUE THREAD

**Issue by TalbotG** [web-platform-tests/wpt#25826] opened 2020-09-29 00:43 UTC
@web-platform-tests/admins 

Dear fellow advanced GitHub colleagues,

2 Continuous Integration checks fail in 
https://github.com/web-platform-tests/wpt/pull/25825
{
Error analysis
Invoke staging.wpt.fyi hook (CmdLine)
Bash exited with code '22'.
}
What's code '22'? 
How to fix whatever is wrong with PR25825? 
What needs to be fixed and how? I wish I could be autonomous when confronting these kinds of failures.
I have no clue where to look, how to find and how to fix over here :( <sigh>.

**Comment by TalbotG** [comment] 2020-09-29 00:53
"Check failure on line 16 in Build log" : how to do that?
Check failure on line 16 in Build log is a link pointing to
https://github.com/web-platform-tests/wpt/pull/25825/files#annotation_466502915
but when activting such link/following it, it does not reach anything specific that can help me.

**Comment by Hexcles** [comment] 2020-09-29 02:04
Sorry for the obscure error message. In short, this is not a blocking issue and you didn't do anything wrong.

Longer version: we run affected tests with and without changes in a PR, upload the results to wpt.fyi as well as its staging instance (staging.wpt.fyi) to show the diff. The staging instance isn't very stable and can sometimes have transient issues as it's meant for the development of wpt.fyi. Arguably failure to upload to staging.wpt.fyi shouldn't show up as a scary error and the message should be more descriptive.

I also just retriggered the run and hopefully the error sign will go away this time.

**Comment by sideshowbarker** [comment] 2020-09-29 02:05
> "Check failure on line 16 in Build log" : how to do that?

https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=55222&view=logs&j=2b63212d-7e76-5e21-f7e5-91768f02360d&t=05da1352-d1c9-5025-5088-2741052b071f is what it‘s actually referring to

…but I don’t think you or other contributors not working on the infrastructure bits could be expected to know that’s where.

> How to fix whatever is wrong with PR25825?

You can’t yourself — as far as I can see, the cause is not a problem with anything in your test, but instead an unexpected failure in some of the ancillary test infrastructure.

So that failure shouldn’t block the test from being merged to the main branch.

> I wish I could be autonomous when confronting these kinds of failures.

You don’t need to the one to troubleshoot those kinds failures. Instead you did the right thing by just alerting others here to the failure. In general, whenever you run into an arcane/esoteric failure like this in the CI stuff, it’s sufficient for you to just give a heads-up to others to point it out.

> Check failure on line 16 in Build log is a link pointing to
> https://github.com/web-platform-tests/wpt/pull/25825/files#annotation_466502915
> but when activating such link/following such link, it does not reach anything specific that can help me.

Yeah, if it’s linking you to that URL, that’s misleading and it shouldn’t be linking to that — because there’s zero info at that URL to show what the problem is.

**Comment by TalbotG** [comment] 2020-09-29 02:31
Okay @Hexcles and @sideshowbarker . I see that CI checks in
https://github.com/web-platform-tests/wpt/pull/25825
have all successfully passed now. I am relieved and happy about this. I have been working on rehabilitating border-image-slice-005 and 007 tests **for 3 years and 10 months** now:

[css-backgrounds-3] border-image-slice-007 bad linkage to its border-image-source
http://lists.w3.org/Archives/Public/public-css-testsuite/2016Dec/0000.html
December 1st 2016

[css-backgrounds-3] border-image-slice-005 bad linkage to its border-image-source
http://lists.w3.org/Archives/Public/public-css-testsuite/2016Dec/0004.html
December 1st 2016

I could close this Issue 25826 now but I think I am going to let you decide about this.

Cheers!

**Comment by sideshowbarker** [comment] 2020-09-29 03:19
Closing now per https://github.com/web-platform-tests/wpt/issues/25826#issuecomment-700388906

**Closed by sideshowbarker** 2020-09-29 03:19 UTC
Labels: GitHub Actions, help, help wanted
