### ISSUE TITLE
Failed to run wpt with --log-mach-level option

### ISSUE THREAD

**Issue by qiuzhong** [web-platform-tests/wpt#14453] opened 2018-12-11 07:54 UTC
From #10512, running `./wpt run --log-mach-level debug firefox websockets/binary/001.html`, we got this error:

```
$  ./wpt run --log-mach-level debug firefox websockets/binary/001.html
Traceback (most recent call last):
  File "./wpt", line 5, in <module>
    wpt.main()
  File "/home/qiuzhong/Workspace/Work/latest/web-platform-tests/wpt/tools/wpt/wpt.py", line 129, in main
    rv = script(*args, **kwargs)
  File "/home/qiuzhong/Workspace/Work/latest/web-platform-tests/wpt/tools/wpt/run.py", line 525, in run
    setup_logging(kwargs)
  File "/home/qiuzhong/Workspace/Work/latest/web-platform-tests/wpt/tools/wpt/run.py", line 470, in setup_logging
    wptrunner.setup_logging(kwargs, default_config)
  File "/home/qiuzhong/Workspace/Work/latest/web-platform-tests/wpt/tools/wptrunner/wptrunner/wptrunner.py", line 41, in setup_logging
    logger = wptlogging.setup(*args, **kwargs)
  File "/home/qiuzhong/Workspace/Work/latest/web-platform-tests/wpt/tools/wptrunner/wptrunner/wptlogging.py", line 16, in setup
    logger = commandline.setup_logging("web-platform-tests", args, defaults)
  File "/home/qiuzhong/Workspace/Work/latest/web-platform-tests/wpt/_venv/lib/python2.7/site-packages/mozlog/commandline.py", line 315, in setup_logging
    setup_handlers(logger, formatters, formatter_options, allow_unused_options)
  File "/home/qiuzhong/Workspace/Work/latest/web-platform-tests/wpt/_venv/lib/python2.7/site-packages/mozlog/commandline.py", line 199, in setup_handlers
    raise ValueError(msg)
ValueError: Options specified for unused formatter(s) (['mach']) have no effect

```

**Comment by gsnedders** [comment] 2018-12-11 14:21
If you pass `--log-mach -` (so the mach logger is used for `stdout`) this should work, I think?

**Comment by qiuzhong** [comment] 2018-12-12 05:49
Yes, `wpt run` with option `--log-mach -` does work.

**Comment by Hexcles** [comment] 2018-12-13 04:37
Closing as it seems to be working as intended. (The default logger is no longer mach.)

**Closed by Hexcles** 2018-12-13 04:37 UTC
Labels: infra, priority:backlog, wptrunner
