### ISSUE TITLE
css/mediaqueries/device-aspect-ratio-{001,005}.html assume device aspect ratio

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#37600] opened 2022-12-20 11:45 UTC
Both these tests seem to assume the aspect ratio is 1280/1024, which seems like a very unfounded assumption. We should probably just remove these tests?

**Comment by nt1m** [comment] 2023-03-10 21:21
Duplicate of #8547

**Closed by nt1m** 2023-03-10 21:21 UTC
Labels: wg-css, mediaqueries
