### ISSUE TITLE
RTCDataChannel-bufferedAmount.html are flawed

### ISSUE THREAD

**Issue by nils-ohlmeier** [web-platform-tests/wpt#10126] opened 2018-03-21 16:54 UTC
@soareschen I looked at why RTCDataChannel-bufferedAmount.html fails on all browser according to https://wpt.fyi/webrtc/RTCDataChannel-bufferedAmount.html even bufferedAmount is implemented at least in Firefox.

I'm pretty sure the problem is the fact that the test calls send() and then expects the bufferedAmount to be exactly the size of the bytes written by the send call. But because the test messages fead into the send calls are pretty small, it is highly likely that the bytes have in fact already been send out over the wire when the test calls the bufferedAmount getter.

I think the only way how you could potentially test this is by trying to send a message with 64k and then verify via the bufferedAmount getter the the buffer is > 0.
But you will never be able to check for an exact sizes in the buffer, because you don't know how fast the underlying data channel is going to be able to send the data off over the network.

@lgrahl might have some ideas on this as well.

**Comment by lgrahl** [comment] 2018-03-21 17:36
What you can check is whether the buffer increases and decreases. I suggest sending 64 KiB (since all browsers are able to cope with that) in a very tight loop (maybe up to a total amount of ~4 MiB). It will always be a race but that should be sufficient to reliably trigger buffering even in a 0-RTT environment (which you have).

Basically, during that loop, if `bufferedAmount <= 0` is true all the time, fail the test.

**Comment by lgrahl** [comment] 2018-03-22 16:52
> I guess one issue we need to address in the spec is whether the underlying implementation is allowed to start performing network operation for an action in parallel as soon as the JS function is called, or whether they can run it only after the JS engine finishes the current microtask and return to the event loop.

IIRC Firefox just lands the data directly in usrsctp's internal buffer if there is space. It continues doing that until it receives `EAGAIN`. To me that is an implementation detail I would not like to specify unless it is a functional requirement and I don't see that here (unless you count probing this for an exact value as a functional requirement).

> _[...] The bufferedAmount attribute MUST, on getting, return the value of the [[BufferedAmount]] slot. The attribute exposes the number of bytes of application data (UTF-8 text and binary data) that have been queued using send() but that, as of the last time the event loop started executing a task, had not yet been transmitted to the network. [...]_

To me this sounds just like: _What you haven't already sent on the wire is in `bufferedAmount`._ I do not understand this as a restriction on when transferring data is allowed. I also want to point out that this section isn't in the actual `send` method - logically, it should be there. No steps of the `send` method mention that there's such a restriction. In fact the note below step 5 states that:

> The actual transmission of data occurs in parallel. If sending data leads to an SCTP-level error, the application will be notified asynchronously through onerror.

So, the question would be what *queueing* implies. I assume we should discuss this further in https://github.com/w3c/webrtc-pc.

**Comment by nils-ohlmeier** [comment] 2018-03-22 17:11
I agree with @lgrahl here that blocking network operations until JS has reached certain check points would be pretty ridiculous. That could lead us then to protocols issues of not being able to respond on the wire to message from the other side, because the network stack is blocked locally on waiting for a JS microtask to finish.

As a counter example: does sending over web sockets ever block and wait for JS micro tasks to finish?

I understand that this makes testing 'bufferedAmount' really hard. But this getter is purely there to allow the JS to find out if the buffer is empty (or close to empty) again, so it can write more data into. It is not intended to allow close monitoring of the buffer size, or even monitoring how fast the data gets send over the wire.

**Comment by soareschen** [comment] 2018-03-23 10:06
I guess I should clarify that by blocking I don't mean that no parallel tasks may be performed while JS is executing a microtask. What I mean is that the local states in the JS land should not be modified in parallel by another thread/process when a microtask is executed.

The current spec does not stop buffers being sent to the network in parallel to the microtask. What it is saying is that there is a local `[[BufferedAmount]]` internal slot that is accessible from JS, which _may_ be different that the actual buffer amount of the underlying implementation. If buffer has been sent in parallel during a microtask execution, the implementation can only update `[[BufferedAmount]]` to sync with the real buffer amount after the current microtask finishes executing. One way this can be achieved is by dispatching another microtask to update `[[BufferedAmount]]` every time the real buffer amount is updated.

The way I see the queue is that it is a concurrent data structure for solving the classic producer consumer problem, or something similar to CSP channel. In the JS land the buffer content is put into the concurrent queue, and at the other side the underlying data transport _may_ read the queue _in parallel_ as the microtask is still running, and send it over the network immediately. _However_, what the underlying data transport should not do is to block the microtask and synchronously does the network operation in the same thread as the JS. If `[[BufferedAmount]]` is always updated by a separate microtask, then we can ensure that the observable value is the same as described in the spec even when data is sent immediately in parallel.

Then again, those are my understanding based on my limited experience and observation on how other people design single threaded JS API to work with concurrent programs. I think the specification matches the behavior I described, but of course we can raise the issue in w3c/webrtc-pc and change the specs to make it easier for browsers to implement the feature, e.g. matching the current behavior of Firefox.

What I think is important is that the spec should specify the semantics of executing concurrent operations, e.g. either always run in parallel using concurrent queue and separate threads, or sometimes blocking JS execution and run synchronously, _but not both_. As we can see here, the source of disagreement is that we have different assumptions on the concurrent behavior which result in very different semantics for the program. If browsers want the option to execute it synchronously, it is important that the spec communicates that possibility so that application developers do not get wrong understanding of the semantics of their programs like I do here.

(Sorry, my background is in programming languages so I tend to go quite into details about semantics and reasoning of program execution)

**Comment by lgrahl** [comment] 2018-03-24 01:03
Having read the description a million times now, your interpretation makes more and more sense. What doesn't make sense to me is the requirement for it being that way. I had a quick look and this sentence is just copied from the WebSockets API.

In any case we should consider rephrasing that description since it has been misinterpreted by at least Randell Jesup, @nils-ohlmeier and me.

**Comment by henbos** [comment] 2018-08-31 08:12
Hey so I haven't read all of the discussion here but I think the spec is fine and Chrome has an implementation bug.

> But because the test messages fead into the send calls are pretty small, it is highly likely that the bytes have in fact already been send out over the wire when the test calls the bufferedAmount getter.

JavaScript pretends to be single threaded and is not allowed to expose the fact that the buffer is being reduced concurrently. So the spec says "When the underlying data transport sends data from its queue, the user agent MUST queue a task that reduces [[BufferedAmount]] with the number of bytes that was sent", meaning that the fact that the buffer has been emptied only becomes visible in the next JavaScript task execution cycle. Also "Even though the data transmission can occur in parallel, the returned value MUST NOT be decreased before the current task yielded back to the event loop to prevent race conditions".

If you do send() and bufferedAmount is not what you've queued to send it's an implementation bug. I don't know about Firefox, but here's the chrome bug: https://crbug.com/878682.

The fact that this fails, e.g.
```
FAIL bufferedAmount should increase to byte length of encoded unicode string sent assert_equals: Expect bufferedAmount to be the byte length of the unicode string expected 12 but got 0
```
Is not a bug in the test but a bug in the implementation.

**Comment by henbos** [comment] 2018-08-31 08:13
I am confident the spec will not change on this point. Can we close this issue and await browser bug fixes?

**Comment by lgrahl** [comment] 2018-08-31 08:31
Yes, this can be closed. My comment earlier was before I understood that reducing the value immediately would create race conditions between the underlying stack running in parallel to a JS task. We have improved the description in https://github.com/w3c/webrtc-pc/pull/1850 to (hopefully) ensure people are more likely to grasp it. (And just FYI, Firefox is also affected.)

**Comment by henbos** [comment] 2018-09-21 08:54
Thanks!

**Closed by henbos** 2018-09-21 08:54 UTC
Labels: webrtc, wg-webrtc
