### ISSUE TITLE
Why is assert_object_equals() failing?

### ISSUE THREAD

**Issue by guest271314** [web-platform-tests/wpt#20844] opened 2019-12-18 17:06 UTC
Why is `assert_object_equals(canvas, ctx.canvas)` failing for https://wpt.fyi/results/imagebitmap-renderingcontext/context-preserves-canvas.html?label=master&label=experimental&aligned&q=imagebitmap-renderingcontext ? See https://github.com/web-platform-tests/wpt/pull/20776#issuecomment-567104621.

**Comment by AmeliaBR** [comment] 2019-12-18 17:37
For reference:

The API description for [`assert_object_equals`](https://web-platform-tests.org/writing-tests/testharness-api.html#assert-object-equals-actual-expected-description):

> asserts that actual is an object and not null and that all enumerable properties on actual are own properties on expected with the same values, recursing if the value is an object and not null.

And the source code:

https://github.com/web-platform-tests/wpt/blob/master/resources/testharness.js#L1143-L1177


As discussed in the linked PR, `assert_object_equals` is actually unnecessary for this test, where you're testing an identity equality. But… it still shouldn't fail! The same object on both sides should have the same enumerable properties. It's possible the problem is somewhere else in that test, though.

**Comment by AmeliaBR** [comment] 2019-12-18 17:47
Looking at the source code, I think the problem is that it's comparing _all_ enumerable properties (`for (p in actual)`) on one object against _own properties_ on the other (` assert(expected.hasOwnProperty(p),`). [Enumerable properties include properties from prototype elements.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in)

**Comment by inexorabletash** [comment] 2020-02-21 18:32
This specific failure (imagebitmap-renderingcontext/context-preserves-canvas.html) was fixed, so closing. The others should be picked off per 2033

**Closed by inexorabletash** 2020-02-21 18:32 UTC
Labels: offscreen-canvas, type:bug
