### ISSUE TITLE
Test failures on macOS due to failing to download ChromeDriver

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#16111] opened 2019-03-27 11:41 UTC
In https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=11342 the "infrastructure/ tests (macOS)" and "tools/wpt/ tests (macOS)" jobs failed because of this error:
> HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/chromium-browser-snapshots/Mac/644709/chromedriver_mac64.zip

I haven't seen this before, and it seems likely to have been caused by https://github.com/web-platform-tests/wpt/pull/15493, so poking @JohnChen0 @Hexcles @jgraham who participated in that review.

The same jobs did pass in the PR itself:
https://github.com/web-platform-tests/wpt/runs/82508511

@JohnChen0 is the new algorithm prone to some race conditions, where the URL tried might not be available yet. Or is there missing macOS-specific logic that's needed to make this work? It would be great if you can investigate this :)

**Comment by JohnChen0** [comment] 2019-03-27 15:06
This appears to be a problem in Chromium's build process. For some reason the ChromeDriver binary is not saved at the end of Mac builds. I'll need to look into our build script to see what is wrong.

**Comment by foolip** [comment] 2019-03-27 15:17
@JohnChen0 do you think this was caused by https://github.com/web-platform-tests/wpt/pull/15493, or would we have tried to fetch this URL before as well?

Short of reverting https://github.com/web-platform-tests/wpt/pull/15493, is there any quickfix for this?

**Comment by Hexcles** [comment] 2019-03-27 15:20
This is definitely caused by #15493 . I thought I verified all platforms (Linux, Mac & Win) but apparently Mac doesn't save chromedriver as an artifact. Hopefully it'd be an easy fix by tweaking the build configuration in Chromium. If John can't spot anything obvious, we can revert #15493 .

**Comment by JohnChen0** [comment] 2019-03-27 19:25
I've found the bug in the Mac build config. Will prepare a fix shortly.

**Comment by JohnChen0** [comment] 2019-03-27 23:27
The fix has been checked into Chromium source repo (https://crrev.com/645038), and we should have a Mac build with ChromeDriver within a few hours.

**Comment by JohnChen0** [comment] 2019-03-28 00:53
The first Mac build with ChromeDriver has been created, with ChromeDriver binary at https://storage.googleapis.com/chromium-browser-snapshots/Mac/645088/chromedriver_mac64.zip.

**Comment by foolip** [comment] 2019-03-28 11:48
@JohnChen0 cool, thanks! Should this fix the problem right away, or does it have to reach the dev channel somehow first?

**Comment by foolip** [comment] 2019-03-28 11:50
I've reopened https://github.com/web-platform-tests/wpt/pull/14887 to see if tests are passing now.

**Comment by Hexcles** [comment] 2019-03-28 15:32
@foolip it should and does work right away. Closing as fixed.

**Closed by Hexcles** 2019-03-28 15:32 UTC
Labels: infra, priority:urgent
