### ISSUE TITLE
Impossible to write .any.js test to be run by service workers with a secure origin

### ISSUE THREAD

**Issue by anitawoodruff** [web-platform-tests/wpt#11105] opened 2018-05-22 17:16 UTC
My new test: 

notifications/interfaces.https.any.js

https://pastebin.com/BG6Xu6Pd

Seems the '.https.' is stripped for service workers which leaves it unable to find the file:

 ```
0:28.90 TEST_START: /notifications/interfaces.https.any.serviceworker.html
 0:29.14 WARNING Traceback (most recent call last):                   
  File "~/web-platform-tests/tools/wptserve/wptserve/handlers.py", line 262, in __call
__                                                                    
    rv = self.func(request, response)                    
  File "~/web-platform-tests/tools/serve/serve.py", line 61, in handle_request
    self.check_exposure(request)                        
  File "~/web-platform-tests/tools/serve/serve.py", line 149, in check_exposure
    for (key, value) in self._get_metadata(request):  
  File "~/web-platform-tests/tools/serve/serve.py", line 102, in _get_metadata
    with open(path, "rb") as f:
IOError: [Errno 2] No such file or directory: '~/web-platform-tests/notifications/inte
rfaces.any.js'
```

@jgraham

**Comment by jgraham** [comment] 2018-05-22 17:19
The problem is that the serviceworker test variant enforces a `https` flag on the resource, which it then removes when looking for the on-disk js file. This is obviously wrong if the js file itself happens to have the `.https.` flag already.

**Comment by anitawoodruff** [comment] 2018-05-23 12:01
And for the record, if I remove '.https.' from the .js test file name, it runs but I get the following failure:

 0:17.77 TEST_START: /notifications/interfaces.https.any.serviceworker.html
 0:18.09 TEST_STATUS: Test OK. Subtests passed 0/1. Unexpected 1
Untitled
--------
Expected PASS, got FAIL
Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).

Only if I duplicate the file both with & without the '.https.' does it run as expected.

**Comment by Ms2ger** [comment] 2018-05-24 15:19
CC @annevk

**Comment by annevk** [comment] 2018-05-24 16:22
If the input file does not contain `.https.`, where does the error "only secure origins are allowed" come from? Is that a problem with Chrome's setup or is some of the infrastructure not aware of `any.js` enabling this? Or both?

Given that you could limit the global to service workers, that does seem like a viable path, but maybe we should disallow it somehow?

Now for the more general problem, where you want `https.any.js`, I guess we could fiddle with `add_mount_point` in `tools/serve/serve.py` a bit.

**Comment by annevk** [comment] 2018-05-24 16:29
Hmm, so if I create `test.https.any.js` that contains
```js
// META: global=serviceworker
console.log("heya");
```
I can load it from `test.https.https.any.serviceworker.html` and it "passes". This is perhaps a little less than ideal URL-wise, but it does work.

I can name the same resource `test.any.js` and load it from the same URL as before with one `.https` less and that also works fine.

We should maybe change it so that if the original URL contains `.https` it doesn't get duplicated, but other than that I'm not sure what's wrong here.

**Comment by jgraham** [comment] 2018-05-24 16:37
What's wrong is that we strip out `https` when going from the serviceworker url to the js path at https://github.com/w3c/web-platform-tests/blob/master/tools/serve/serve.py#L232. We need to fix things so that the `.https.` isn't stripped in this case.

**Comment by anitawoodruff** [comment] 2018-05-24 16:39
@annevk in your testing were you writing the .html files by hand? I was relying on the auto-generated html files that appear to get generated when running with the 'any.js' file as the target (and I guess that's where the serve.py bug breaks things..?)

**Comment by annevk** [comment] 2018-05-24 16:47
All I created were the `test.https.any.js` and later `test.any.js` resources.

@jgraham I think that's only because you load it from `test.https.any.serviceworker.html` instead of `test.https.https.any.serviceworker.html`. With the latter it works. One bug with the former though is that it generates a 500 instead of a 404, so there's definitely some room for improvement here.

**Comment by anitawoodruff** [comment] 2018-05-24 17:37
Ah I see. And how are you running the tests? (I am using `wpt run mytestname.any.js`, I don't really understand how to use `wpt serve`)

**Comment by jgraham** [comment] 2018-05-24 17:49
https://github.com/w3c/web-platform-tests/pull/11151 is a not-great fix here.

Loading the test from `test.https.https.any.serviceworker.html` is wrong because that's not what's in the manifest and violates the assumption that `.https.` works like a flag. Also it's super ugly.

**Comment by annevk** [comment] 2018-05-25 06:13
@jgraham if it's wrong it shouldn't succeed.

@anitawoodruff I keep `./wpt serve` running usually and then browse to `https://web-platform.test:8443/...`.

**Comment by foolip** [comment] 2018-06-07 13:05
@anitawoodruff is this still creating trouble for you, or is there a workaround that makes it bearable?

@annevk @jgraham will you battle it out in https://github.com/web-platform-tests/wpt/pull/11151, or are there other options here?

**Comment by anitawoodruff** [comment] 2018-07-09 13:49
@foolip My only workaround atm is to have two copies of the test - `interfaces.https.any.js`& `interfaces.any.js`, with an explanatory comment in both, see https://github.com/web-platform-tests/wpt/pull/11122 . I don't know whether this counts as 'bearable'; I guess it's up to the reviewers..

(btw how do wpt reviews work? If I'm making spec changes will the spec change reviewer(s) review the tests at the same time?)

**Comment by lukebjerring** [comment] 2018-07-11 16:03
I also hit this issue authoring https://github.com/web-platform-tests/wpt/issues/11925, and had to drop the .https. from the test.

**Comment by foolip** [comment] 2018-07-20 13:54
> btw how do wpt reviews work? If I'm making spec changes will the spec change reviewer(s) review the tests at the same time?

This isn't entirely uniform and depends on the spec and people involved. For specs listed in https://github.com/foolip/testing-in-standards/blob/master/policy.md and hopefully more, editors won't merge the spec change until there are corresponding tests, and will probably review your tests as well.

I'll ping https://github.com/web-platform-tests/wpt/pull/11151, duplicating tests doesn't sound fun.

**Comment by jgraham** [comment] 2018-08-09 14:59
This is causing surprising test timeouts in gecko infra (and probably everywhere else too).

The fundamental issue is that we assume a 1:1 mapping between `.any.js` inputs and generated test paths. But, by generating an implicit `https` test from a non-https URL we break that assumption.

One possible solution is just to make `.serviceworker.` imply that the test is loaded over https directly without also having to add `.https.` to the url. Assuming that works the way I think it ought to, the "only" problem is that it breaks incremental manifest updates because the tests generated are changed but the file content remains the same.

**Comment by Hexcles** [comment] 2018-08-12 16:36
I assume this is fixed by #12381?

**Comment by Ms2ger** [comment] 2018-08-13 08:28
Same.

**Closed by Ms2ger** 2018-08-13 08:28 UTC
Labels: infra, priority:urgent

**Comment by annevk** [comment] 2018-08-13 09:25
There was a question by @foolip on IRC whether we wanted to make any.js imply HTTPS, but maybe that's tracked separately or less important now. (I'm happy with the (new) status quo.)

**Comment by Ms2ger** [comment] 2018-08-13 09:49
I don't think we want to, but someone could file a separate issue to discuss that.

**Comment by foolip** [comment] 2018-08-13 12:18
What I suggested on IRC was requiring .http.any.js for global=serviceworker so that the problem in this issue would go away. But that would make it impossible to have the same test run in both a secure and non-secure context, and would get in the way of adding some syntax for having a single test run in secure and non-secure contexts, like maybe `context=http,https`. I'm happy enough with the new status quo, but agree with https://github.com/web-platform-tests/wpt/issues/12379 filed by @gsnedders.
