### ISSUE TITLE
Safari Technology Preview failed on Azure because remote automation isn't enabled

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt#20731] opened 2019-12-11 22:52 UTC
Example: https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=38701&view=logs

> SessionNotCreatedException: session not created (500): Could not create a session: You must enable the 'Allow Remote Automation' option in Safari's Develop menu to control Safari via WebDriver.

Only one of the shards had this error. cc @foolip

**Comment by foolip** [comment] 2019-12-12 15:45
I don't know why this happened, but it only happened once, so downgrading from urgent.

**Comment by foolip** [comment] 2019-12-13 08:58
It happened again in https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=38806, but it did succeed again on a later build.

There's no indication in the "Install Safari Technology Preview" step that anything went wrong with `sudo "/Applications/Safari Technology Preview.app/Contents/MacOS/safaridriver" --enable`.

Looking at "Initialize job" in the two failure cases, it's not the same "Agent machine name" (Mac-1127 vs Mac-1149) so I wouldn't bet that this is a problem with a specific agent. Nevertheless, @mustjab is there any way to check if these agents are healthy, or have had a higher rate of failure than usual?

My best guess at this point is a `safaridriver --enable` bug, perhaps there's some part of it that's racy or some rare condition where it thinks the setting is already enabled and does nothing. This is pure speculation though.

@burg would verbose safaridriver logs for a case where this has happened likely reveal what the problem is? It seems to me it's likely the `safaridriver --enable` step that hasn't worked, can verbose logging for that step itself be enabled?

**Comment by burg** [comment] 2019-12-13 09:50
Yes, there is lots of logging related to --enable flag. Verbose logging to Console.app can be enabled via --diagnose or `defaults write com.apple.WebDriver DiagnosticsEnabled -bool YES`.

**Comment by mustjab** [comment] 2019-12-13 15:14
I can only see the Agent history (Azure Pipelines 3 agent) and it appears to have been stable except for that run recently: https://dev.azure.com/web-platform-tests/wpt/_settings/agentqueues?agentId=275&queueId=21&view=jobs

**Comment by foolip** [comment] 2019-12-13 15:32
@burg I tried `sudo /Applications/Safari\ Technology\ Preview.app/Contents/MacOS/safaridriver --enable --diagnose` locally, but it doesn't print anything to stdout and ~/Library/Logs/com.apple.WebDriver/ doesn't exist, neither for my normal user nor the root user.

Am I doing it wrong? :)

**Comment by burg** [comment] 2020-01-06 20:25
@foolip I confirmed locally, this seems to be a bug 🙃 I've created an internal bug report and hopefully can figure it out before too long.

In the meantime, Console.app / `log` should still be logging diagnostics to the com.apple.WebDriver subsystem.

**Comment by burg** [comment] 2020-01-06 20:26
Tracked internally as <rdar://problem/58350296> `safaridriver --diagnose --enable` should produce diagnostic logs, but doesn't

**Comment by burg** [comment] 2020-01-10 00:25
Upon more investigation.. it's not expected to create files in ~/Logs/  for problems with --enable. The diagnostic files logged to ~/Logs/com.apple.WebDriver/ are for protocol and HTTP tracing only.

In the case of a problem with --enable you can look in Console.app with the 'com.apple.WebDriver' subsystem to see the debug logging. This is also included in a sysdiagnose.

**Comment by foolip** [comment] 2020-01-16 09:42
@burg it sounds like we might be best off waiting for rdar://problem/58350296 to be resolved, since this problem hasn't been recurring. Still, I wonder how to "look in Console.app with the 'com.apple.WebDriver' subsystem" in a CI setup? Is there a shell command that would dump this output, or is that precisely sysdiagnose?

**Comment by burg** [comment] 2020-01-17 21:18
This can be done with:

	log stream --info --debug --predicate="subsystem is 'com.apple.WebDriver'"

**Comment by foolip** [comment] 2020-01-20 09:31
@burg when I run that locally (macOS 10.15.1) I get the error `log: Bad predicate (Unable to parse the format string "subsystem is 'com.apple.WebDriver'"): subsystem is 'com.apple.WebDriver'`. Removing the single quotes didn't fix it, not sure what else to try.

This isn't urgent at all to figure out because right now we don't have a need to add logging to Azure Pipelines.

**Comment by foolip** [comment] 2020-02-12 09:06
I'm closing this in favor of https://github.com/web-platform-tests/wpt/issues/21751, as the problem now affects both STP and Safari stable.

**Closed by foolip** 2020-02-12 09:06 UTC
Labels: Azure Pipelines, infra, priority:roadmap
