### ISSUE TITLE
WebKitGTK runs missing since August 23

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt#35659] opened 2022-08-27 00:35 UTC
[WebKitGTK runs missing since August 23](https://wpt.fyi/runs?label=master&label=experimental&max-count=100&product=chrome&product=edge&product=firefox&product=safari&product=webkitgtk&view=subtest). @clopez would you mind taking a look? Thanks!

**Comment by clopez** [comment] 2022-09-02 18:51
It seems there is a problem with github actions that is queuing completed jobs forever. And is not only happening to webkitgtk, but also to other browsers.

The runs itself on taskcluster are working fine and finishing with green status (completed). The problem is on github actions processing the runs from taskcluster.

I'm going to paste here two examples of this, one older than a week (to show that the runs are still waiting to be processed on GH after more than a week) and other one more recent.

**Example 1) This should have finished 8 days ago but is still queued on github.**

- Date of run: 25th of August
- Commit that triggers it: 54e987971bb1a28785849ba1805a45344527927e
- Github actions link: https://github.com/web-platform-tests/wpt/runs/8003836982
  - Check at the left right that all webkitgtk_minibrowser runs have finished correctly except some of them that have a brown circle and say "This check is queued" if you hover the mouse over the circle.
  - Open the runs that have the brown circle to see what taskcluster says and see how all of them have finished with green status (completed):
    - https://community-tc.services.mozilla.com/tasks/PYVauQejSI6mrr9SOSUkog
    - https://community-tc.services.mozilla.com/tasks/BS4e33TgS7asICFYkOzZQA
    - https://community-tc.services.mozilla.com/tasks/f6INZdOPQA6bJbmvPMW1zg
    - https://community-tc.services.mozilla.com/tasks/VV8s1hq3SQygaX7Vx8Ot3A

**Example 2) The daily run from yesterday**

- Date of run: 1th of September
- Commit that triggers it: d69fbacf94a8f6185ea784d397c1799bacfbc4f2
- Github actions link: https://github.com/web-platform-tests/wpt/runs/8126782804
  - Check at the left right that all webkitgtk_minibrowser runs have finished correctly except some of them that have a brown circle and say "This check is queued" if you hover the mouse over the circle.
  - Open the runs that have the brown circle to see what taskcluster says and see how all of them have finished with green status (completed):
    - https://community-tc.services.mozilla.com/tasks/VVUGTTVfSxemoNv06UkPnA
    - https://community-tc.services.mozilla.com/tasks/QH0AJHcKT6SaiFxRFoihhQ

**Comment by clopez** [comment] 2022-09-08 11:48
I don't know what has caused this on github. Maybe it was an issue on their end (github).

But for some reason, the runs have started to work back on 5th of september.

Let's wait another week to see if the problem appears again before closing the issue.

**Comment by clopez** [comment] 2022-10-03 10:42
Closing this. Runs seem to be running fine

**Closed by clopez** 2022-10-03 10:42 UTC
