### ISSUE TITLE
[WebIDL] 'void' type is changing to 'undefined'

### ISSUE THREAD

**Issue by tabatkins** [web-platform-tests/wpt#25014] opened 2020-08-14 17:49 UTC
As part of efforts to finally add an 'undefined' type to WebIDL (so methods/etc don't have to generalize their type to 'any'), it was decided to actually add 'undefined' as the type name, and so the previous function return signature 'void' is being removed for redundancy.

See https://github.com/heycam/webidl/pull/906 for details on the change.

This change will be merged shortly; this bug is a heads-up to adjust your IDL parser (see the PR for the changes to the grammar; it's quite small).

**Comment by stephenmcgruer** [comment] 2021-02-22 17:04
Dupe of https://github.com/web-platform-tests/wpt/issues/25015 ?

**Closed by stephenmcgruer** 2021-02-22 17:04 UTC
Labels: idlharness.js, infra
