### ISSUE TITLE
Azure Pipeline run queued and not restarted

### ISSUE THREAD

**Issue by TalbotG** [web-platform-tests/wpt#46378] opened 2024-05-20 20:07 UTC
@foolip , @jcscottiii , @gsnedders , @whimboo

Dear github admins and fellow colleagues,

In [Pull Request 42345](https://github.com/web-platform-tests/wpt/pull/42345) , commit https://github.com/web-platform-tests/wpt/pull/42345/commits/b1191447d79a15f46da9621c2f1d33d803049c62 failed and I do not know why. 

After searching, I end up in this [Azure Pipeline page](https://github.com/web-platform-tests/wpt/runs/25140115232) or in this [Azure Pipeline Run page](https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=123694&view=results) and I still can not figure out why the commit https://github.com/web-platform-tests/wpt/pull/42345/commits/b1191447d79a15f46da9621c2f1d33d803049c62 failed and what his author , @SebastianZ , can do and should do.

**Comment by whimboo** [comment] 2024-05-21 07:21
@TalbotG I don't know what the problem is. But what we usually do is to close and reopen a PR to re-trigger all the checks. That's the first thing that I would suggest to do. If that doesn't help maybe someone else has more ideas.

**Comment by foolip** [comment] 2024-05-21 13:17
I see that the checks are passing on the PR now.

In https://github.com/web-platform-tests/wpt/runs/25140134004 (for commit b1191447d79a15f46da9621c2f1d33d803049c62) I think the problem was actually that the Taskcluster tasks were cancelled for some reason.

Closing this as the problem did not persist.

**Comment by TalbotG** [comment] 2024-05-21 14:50
> I see that the checks are passing on the PR now.

@foolip Philip, 

Where exactly do you see that the checks are passing or have passed? 

When I visit https://github.com/web-platform-tests/wpt/pull/42345/commits/b1191447d79a15f46da9621c2f1d33d803049c62 I see:

"
Some checks were not successful
10 cancelled, 1 queued, and 3 successful checks 
" 

and when I visit

https://github.com/web-platform-tests/wpt/runs/25140134004

I see a red circle with some green at top-left corner

The commit is preceded by a red "x" in the https://github.com/web-platform-tests/wpt/pull/42345 page

**Comment by TalbotG** [comment] 2024-05-21 14:53
> what we usually do is to close and reopen a PR to re-trigger all the checks

@whimboo Henrik, 
Please visit https://github.com/web-platform-tests/wpt/issues/45943 and support item 2 because what you suggest is not in documentation and, in my opinion, it should.

**Comment by foolip** [comment] 2024-05-21 22:05
@TalbotG if I scroll to the end of https://github.com/web-platform-tests/wpt/pull/42345 I see "All checks have passed". That's because the tip of the PR branch is now commit 48b9f4acb5caee1f54b6610cb9b8217c3652bc94, any failures previously don't block the PR.

**Comment by TalbotG** [comment] 2024-05-22 00:46
> if I scroll to the end of https://github.com/web-platform-tests/wpt/pull/42345 I see "All checks have passed".

I do see "All checks have passed" but that is for the last commit, which is [commit 48b9f4a](https://github.com/web-platform-tests/wpt/pull/42345/commits/48b9f4acb5caee1f54b6610cb9b8217c3652bc94) .

When I visit again https://github.com/web-platform-tests/wpt/commit/b1191447d79a15f46da9621c2f1d33d803049c62 I still see:

"
Some checks were not successful
10 cancelled, 1 queued, and 3 successful checks
"

When I visit again

https://github.com/web-platform-tests/wpt/runs/25140134004

I still see a red circle with some green at top-left corner.

>  any failures previously don't block the PR.

But what about commit https://github.com/web-platform-tests/wpt/commit/b1191447d79a15f46da9621c2f1d33d803049c62 ? It will not register. It will not modify the tests. Submiting the PR will not register, will not embed commit https://github.com/web-platform-tests/wpt/commit/b1191447d79a15f46da9621c2f1d33d803049c62

There are 18 commits in PR42345. Only 17 commits will modify the tests. The commit https://github.com/web-platform-tests/wpt/commit/b1191447d79a15f46da9621c2f1d33d803049c62 will not modify the tests because of what I quoted up here.

**Comment by TalbotG** [comment] 2024-05-22 00:52
The "Re-run all checks" button does not work for a particular, specific commit. It only works for the last commit.

**Comment by TalbotG** [comment] 2024-05-22 00:58
What does "This run will be cleaned up after 10 days based on your project settings." mean?
I see this in
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=123694&view=results

**Comment by whimboo** [comment] 2024-05-22 06:05
> taskcluster/github does not have sufficient scopes and is missing the following scopes: (...)" which must be related to my attemps to re-run the checks for commit [b119144](https://github.com/web-platform-tests/wpt/commit/b1191447d79a15f46da9621c2f1d33d803049c62)

Yes, that is correct. As I stated earlier you have to close and reopen the PR to trigger the checks again.

**Comment by TalbotG** [comment] 2024-05-22 19:26
Henrik,

I closed and reopened [Pull Request 42345](https://github.com/web-platform-tests/wpt/pull/42345) a few min ago. The 19 Continuous Integration checks started, ran (but I did not see which commit it was running on) and when I visit again https://github.com/web-platform-tests/wpt/commit/b1191447d79a15f46da9621c2f1d33d803049c62 , I still see:
"
Some checks were not successful
10 cancelled, 1 queued, and 3 successful checks
"
and still see a red circle with some green at top-left corner in 
https://github.com/web-platform-tests/wpt/runs/25140134004

**Comment by foolip** [comment] 2024-05-22 19:40
@TalbotG the PR is once again passing the checks. If you get it reviewed and still can't merge it, let me know and I can check why CI is failing.

**Comment by TalbotG** [comment] 2024-05-22 21:26
Philip,

I am mostly concerned about the changes, the modifications in commit [b119144](https://github.com/web-platform-tests/wpt/commit/b1191447d79a15f46da9621c2f1d33d803049c62) if I review and approve the PR. I want the changes and modifications (removing the margin-top as the label given to the commit states) to be registered, to be carried over (I can not find the correct verb here) when I approve and merge the #42345.

Anyway... I will try to approve and to merge the #42345 tomorrow.

**Comment by foolip** [comment] 2024-05-23 18:16
@TalbotG if the checks are passing on the pull request and you squash all the commits when you merge, then none of the original commits will really matter. The CI failures that were on the branch also don't get in the way of merging as long as they're fixed in subsequent commits.

**Closed** 2024-05-28 17:26 UTC
Labels: help wanted, Azure Pipelines, help

**Comment by whimboo** [comment] 2024-05-28 19:35
Sounds good. Thanks for letting us know!
