### ISSUE TITLE
WPT test css/css-flexbox/overflow-auto-006.html has a number of problems

### ISSUE THREAD

**Issue by dholbert** [web-platform-tests/wpt#22580] opened 2020-03-31 21:37 UTC
This recently-added WPT test has a number of problems.

WPT.fyi link to view results:
https://wpt.fyi/results/css/css-flexbox/overflow-auto-006.html?label=experimental&label=master&aligned

WPT.live link to run the test directly:
https://wpt.live/css/css-flexbox/overflow-auto-006.html

(1) While it passes in Chrome, it fails if you view it with 200% zoom level, which is a sign that it might have some rounding issues.

(2) Pieces of the test are too small for scrollbars to show up in, on some platforms (at least, that seems to be the case when I run the test under Firefox's test-runner on my HiDPI machine -- this uses tiny 100%-pixel-scaling content but large-and-usable scrollbars, which should be fine, but seems to make this test fail.)

(3) Subtests 3,4, 9,10,13,14 fail in every browser besides Chrome, due to these subtests assuming that `overflow:auto` elements should contribute their scrollbar thickness to their intrinsic size. See https://bugzilla.mozilla.org/show_bug.cgi?id=764076#c7 for why this is problematic (tl;dr: the spec doesn't mandate any particular behavior & says it's UA-dependent as long as overflowing content is reachable via scrolling mechanism)

**Comment by dholbert** [comment] 2020-03-31 21:39
CC @cbiesinger @davidsgrogan @tonikitoo

**Comment by dholbert** [comment] 2020-03-31 21:47
(2) Pieces of the test are too small for scrollbars to show up in, on some platforms

(On my machine at least, category (2) is responsible for subtests 1, 2, 5, 6, 11, and 12 failing in Firefox, I'm pretty sure. I noticed that all of these subtests fail in Firefox 76 as well as [chromium-based] Edge 83, according to WPT.fyi, so this isn't just a Firefox-specific problem, too.)

**Comment by tonikitoo** [comment] 2020-04-01 17:14
just to be sure, (1)(2) could be addressed on the test itself, being (2) more important than (1), whereas (3) needs UA to be "fixed" by the engine itself, in case it is wanted/agreed, right?

**Comment by Hexcles** [comment] 2020-04-01 17:19
Re (3) if the spec explicitly says the behaviour is UA-dependent, tests should not assert one way or another -- in other words, we probably want to remove those tests.

**Comment by davidsgrogan** [comment] 2020-04-01 17:45
I'm only seeing (3) failures, 3,4,9,10,13,14 in Firefox, both locally and on wpt.fyi, no (2) failures at all, and no (1) failures at any zoom level. And it appears Edge passes all the tests on wpt.fyi.

Are (2) failures only visible in firefox's test-runner on a hidpi machine?

Was there an update to the test since @dholbert posted his findings yesterday?

**Comment by Hexcles** [comment] 2020-04-01 17:46
> And it appears Edge passes all the tests on wpt.fyi.

Note that is the Chromium-based Edge.

**Comment by davidsgrogan** [comment] 2020-04-01 17:49
> > And it appears Edge passes all the tests on wpt.fyi.
> 
> Note that is the Chromium-based Edge.

Agreed, but it was chromium-based Edge mentioned in https://github.com/web-platform-tests/wpt/issues/22580#issuecomment-606894495

**Comment by Hexcles** [comment] 2020-04-01 17:53
Ahh sorry I missed that.

I think @dholbert filed this issue before @tonikitoo 's fix 53531853234b44c8ced9e2e6c4b4a3ab381b6279

Before fix:
https://wpt.fyi/results/css/css-flexbox/overflow-auto-006.html?sha=1e0302fe&label=master&label=experimental
After fix:
https://wpt.fyi/results/css/css-flexbox/overflow-auto-006.html?sha=82d8c52&label=experimental&label=master

**Comment by davidsgrogan** [comment] 2020-04-01 17:57
Ah, and I missed that that fix was for this issue. Sorry, and thanks for pointing it out.

**Comment by dholbert** [comment] 2020-04-01 21:53
Thanks everyone - looking at the "After fix" wpt.fyi link, it does indeed look like the only remaining failures here are the "category (3)" failures (3/4/9/10/13/14), and per https://github.com/web-platform-tests/wpt/issues/22580#issuecomment-607381316 those tests should probably be removed or relaxed.

**Comment by Hexcles** [comment] 2020-04-02 19:09
@tonikitoo could you take care of moving the subtests in category 3 back to Chromium? Thanks!

**Comment by tonikitoo** [comment] 2020-04-02 19:33
yes, sir. will handle it shortly

**Comment by tonikitoo** [comment] 2020-04-03 17:50
category 3 should be fixed by PR #22094 

@dholbert I believe we might need to mark the test in FF as PASS'ing as a follow up, eventually (once the sync-bot syncs).

**Comment by Hexcles** [comment] 2020-04-06 16:58
#22688 has been merged, so I'm closing this issue.

@dholbert : I'm sorry for the recent hiccups in our effort to upstream some Chromium-internal flexbox tests, which unfortunately have caused quite some extra work for you. We did intend to keep an eye on the test results on other browsers and investigate any failure before landing a test. However, due to an oversight and bad UI of our wpt.fyi GitHub checks, people only paid attention to regressions but not new failures. We've identified the problem and @tonikitoo has volunteered to review all exported PRs recently. Thanks for being patient with us and filing these issues, and sorry again for the trouble.

**Closed by Hexcles** 2020-04-06 16:58 UTC

**Comment by dholbert** [comment] 2020-04-06 17:05
Understood. I'm glad there's an improved process to catch these sorts of issues up-front going forward.  Thanks to you folks for you responsiveness over the past week!
