### ISSUE TITLE
[wdspec] /webdriver/tests/bidi/browsing_context/reload/ is flaky in Chromium

### ISSUE THREAD

**Issue by OrKoN** [web-platform-tests/wpt#41083] opened 2023-07-18 07:37 UTC
See https://github.com/web-platform-tests/wpt/pull/41041/checks?check_run_id=15094630093

It appears that reload tests are flaky in Chromium.

- [x] `reload.py`
- [x] `frame.py`

**Comment by whimboo** [comment] 2023-08-31 12:53
I've noticed the same today and did some quick checks. The problem seems to happen only when more than one test method in that module gets run. Running each test on its own doesn't produce this failure. It seems that some unexpected content might be sent by chromedriver?

This can be reproduced locally as well, but cannot tell more details because I'm not able to enable any debug/trace logs for chromedriver.

**Comment by thiagowfx** [comment] 2023-08-31 13:12
@whimboo Do you observe the failure in Geckodriver?

**Comment by whimboo** [comment] 2023-08-31 17:29
We do not have reload implemented yet. So all these tests are failing with an unknown operation error. That means I cannot test it at the moment. Are you able to reproduce it locally when running the following command with a Canary build of Chrome?

> ./wpt run chrome webdriver/tests/bidi/browsing_context/reload/reload.py --channel=nightly

**Comment by whimboo** [comment] 2023-09-05 10:16
The problem here is most likely present because the initial navigation is not awaited for. As such the reload is started while the current page is still loading, which then can cause side-effects.

https://github.com/web-platform-tests/wpt/blame/c6e26d40406b88796028c912d3051a869a557647/webdriver/tests/bidi/browsing_context/reload/reload.py#L12-L13

I'm going to fix that on https://bugzilla.mozilla.org/show_bug.cgi?id=1830859, and I hope that this is enough here.

**Comment by thiagowfx** [comment] 2023-09-05 10:38
Thanks for the investigation!

**Comment by whimboo** [comment] 2023-09-07 06:39
FYI the updated tests will be available once https://github.com/web-platform-tests/wpt/pull/41841 has been merged.

**Comment by thiagowfx** [comment] 2023-09-07 08:29
I made some comments there. Thanks!

**Comment by whimboo** [comment] 2023-09-07 09:32
The PR has been merged now. Not sure if your wrapper already supports returning a `NavigationResult` instead of `EmptyResult`. If not maybe you can check if it is still flaky?

**Comment by thiagowfx** [comment] 2023-09-07 11:17
Let's see: https://github.com/GoogleChromeLabs/chromium-bidi/pull/1264

**Comment by thiagowfx** [comment] 2023-09-07 12:50
`frame.py` is still flaky. But `reload.py` seems to be OK now! (pending more runs to increase confidence)

**Comment by whimboo** [comment] 2023-09-11 10:07
@thiagowfx please note that from the log output it is not clear why or where it is timing out. Are these both tests or maybe only the cross-origin test case?

**Comment by thiagowfx** [comment] 2023-09-11 20:05
My understanding is: same-origin seems to be executed first (as it's listed first), and the timeout happens there already.

**Comment by whimboo** [comment] 2023-09-12 06:18
Ok, so it only happens in CI and you cannot reproduce locally? If that is the case do you have a chance to somehow enable debug/trace logging for the tests? Where exactly does it hang/timeout?

**Comment by thiagowfx** [comment] 2023-09-12 19:13
Running it locally in our mapper repo (`npm run wpt -- webdriver/tests/bidi/browsing_context/reload/frame.py`) seems to consistently pass. This is a CI-only failure, that's correct.

I am not quite sure how to debug it. I'll try. https://github.com/GoogleChromeLabs/chromium-bidi/pull/1288

**Comment by thiagowfx** [comment] 2023-09-12 19:44
I have the impression it's not flaky anymore: https://github.com/GoogleChromeLabs/chromium-bidi/pull/1288. Hope not to be speaking too soon...will reopen if it turns out to be wrong.

**Closed by thiagowfx** 2023-09-12 19:44 UTC

**Comment by V-kremenlieva** [comment] 2023-09-13 06:56
Js
