### ISSUE TITLE
Is the Certificate Authority name-constrained somehow?

### ISSUE THREAD

**Issue by annevk** [web-platform-tests/wpt#11075] opened 2018-05-18 16:35 UTC
I wonder if the Certificate Authority we have to add to root stores to work with web-platform-tests is name-constrained somehow or if an attacker can use it mint certificates.

**Comment by annevk** [comment] 2018-05-18 16:43
As far as I can tell this is not the case and therefore everyone that has added this root certificate is susceptible to attacks... https://tools.ietf.org/html/rfc5280#section-4.2.1.10 describes name constraints, but I'm not really familiar enough with them to fix this myself.

**Comment by gsnedders** [comment] 2018-05-21 14:11
Do we actually add a CA? I thought we just added individual certificates, and not a root cert?

**Comment by jgraham** [comment] 2018-05-21 14:19
Hmm, so the urgent part of this is probably updating the README to note that you should never use the certificates in a profile you use for other browsing. I thought it said that already, but I was wrong.

**Comment by gsnedders** [comment] 2018-05-21 14:21
I would have assumed we didn't set the cA boolean, in which case I thought none of this applied? (Like, we can't even set name constraints if cA is false/omitted.)

**Comment by gsnedders** [comment] 2018-05-21 14:22
Or does that only affect intermediate certs?

**Comment by gsnedders** [comment] 2018-05-21 14:28
> Hmm, so the urgent part of this is probably updating the README to note that you should never use the certificates in a profile you use for other browsing.

That doesn't work for browsers that rely on the OS cert store (Chrome, Edge, Safari); you can't create a separate profile short of creating a new OS user account.

**Comment by jgraham** [comment] 2018-05-21 14:30
I mean I agree we should fix the bug; I had no idea that this feature even existed. But yeah, you shouldn't test those browsers except in a VM, unless you use `wpt run` which avoids the problem by disabling certificate checking.

**Comment by gsnedders** [comment] 2018-05-21 14:33
> you use wpt run which avoids the problem by disabling certificate checking

(We only do that in Firefox, so for other browsers you still need to install it.)

**Comment by jgraham** [comment] 2018-05-21 14:35
That isn't true.

**Comment by jgraham** [comment] 2018-05-21 14:36
https://github.com/w3c/web-platform-tests/pull/11094 for the warning.

**Comment by annevk** [comment] 2018-05-29 03:13
It should be fairly trivial to fix the certificate to not have this problem and not require dedicated VMs to run simple tests. I don't understand why we don't focus on that as it seems much more likely folks run tests that way.

**Comment by gsnedders** [comment] 2018-05-30 17:19
@annevk I think half the problem is those of us who largely own `/tools` don't have a good comprehension of the OpenSSL interface to generate a new cert (nor being entirely sure how the existing CA cert or pregenerated certs were generated), FWIW, and whether it's easier to try and get someone who does understand what's needed to get the right thing out than spend a while trying to figure it out ourselves, especially when there's other things needing done.

**Comment by annevk** [comment] 2018-05-30 17:39
Yeah, I shouldn't have said fairly trivial, since I looked around a fair bit and there's not much advice on name constraining available. Sorry about that. I will ask around a bit and see if I can get some help.

**Comment by gsnedders** [comment] 2018-05-30 17:41
To note: part of updating the certs should probably include writing something along the lines of "here's how you update these", with any openssl x509_config files or similar checked in.

**Comment by jgraham** [comment] 2018-05-30 17:44
I tried a patch where the significant part was:
```
+        constraints_line = "\n".join("nameConstraints = permitted;%s" % item
+                                     for item in alt_names.split(","))
```

but afaict that didn't work (and multiple comma-separated san formatted hosts on the same line didn't seem to parse).


@gsnedders The way you are supposed to do it is set up the server config to use OpenSSL and have a duration of much longer than the default 30 days. It's true that that isn't documented (and also that your config changes broke it), but it is already all in the repository. One can imagine adding a `wpt make-certs` command.

**Comment by mozkeeler** [comment] 2018-05-30 17:49
@jgraham I think the format has to be `nameConstraints = permitted;DNS:some.domain,DNS:other.domain,...` (extrapolated from https://www.openssl.org/docs/man1.0.2/apps/x509v3_config.html )

**Comment by jgraham** [comment] 2018-05-30 18:23
I set it up like

```
[ v3_ca ]
basicConstraints = CA:true
subjectKeyIdentifier=hash
authorityKeyIdentifier=keyid:always,issuer:always
keyUsage = keyCertSign
nameConstraints = permitted;DNS:web-platform.test,DNS:not-web-platform.test,DNS:www.web-platform.test,DNS:www1.web-platform.test,DNS:www2.web-platform.test,DNS:www.not-web-platform.test,DNS:www2.not-web-platform.test,DNS:www1.not-web-platform.test,DNS:xn--lve-6lad.web-platform.test,DNS:xn--lve-6lad.not-web-platform.test,DNS:xn--n8j6ds53lwwkrqhv28a.web-platform.test,DNS:xn--n8j6ds53lwwkrqhv28a.not-web-platform.test
```

But if I do `openssl x509 -in /home/james/develop/web-platform-tests/_certs/cacert.pem -text` I don't see much of anything about nameConstraints:

```
        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:TRUE
            X509v3 Subject Key Identifier: 
                69:A2:C8:8F:D7:F9:65:22:4C:5E:82:DE:C3:93:FB:FD:84:D7:82:F0
            X509v3 Authority Key Identifier: 
                keyid:69:A2:C8:8F:D7:F9:65:22:4C:5E:82:DE:C3:93:FB:FD:84:D7:82:F0
                DirName:/CN=web-platform-tests
                serial:05:CE:A3

            X509v3 Key Usage: 
                Certificate Sign
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication
```

**Comment by jgraham** [comment] 2018-05-30 18:33
Oh, oops, that was an old version of the file. Now I'm back to getting a syntax error:
```
'Error Loading extension section v3_ca\n139712000577984:error:2209308F:X509 V3 routines:v2i_NAME_CONSTRAINTS:invalid syntax:../crypto/x509v3/v3_ncons.c:127:\n139712000577984:error:22098080:X509 V3 routines:X509V3_EXT_nconf:error in extension:../crypto/x509v3/v3_conf.c:47:name=nameConstraints, value=permitted;DNS:web-platform.test,DNS:not-web-platform.test,DNS:www.web-platform.test,DNS:www1.web-platform.test,DNS:www2.web-platform.test,DNS:www.not-web-platform.test,DNS:www2.not-web-platform.test,DNS:www1.not-web-platform.test,DNS:xn--lve-6lad.web-platform.test,DNS:xn--lve-6lad.not-web-platform.test,DNS:xn--n8j6ds53lwwkrqhv28a.web-platform.test,DNS:xn--n8j6ds53lwwkrqhv28a.not-web-platform.test\n'
```

**Comment by foolip** [comment] 2018-06-11 10:04
@annevk, you added the urgent label to this, which will make it show up in https://foolip.github.io/ecosystem-infra-rotation/ every two days without activity. Who should the assignee be of this?

**Comment by annevk** [comment] 2018-06-12 13:09
I don't know, someone who knows enough about OpenSSL to help make this happen.

**Comment by gsnedders** [comment] 2018-06-14 15:23
@foolip pretty sure that a) he set up it originally; b) none of us really know enough

**Comment by foolip** [comment] 2018-09-25 09:11
@jgraham, in https://github.com/web-platform-tests/wpt/issues/11075#issuecomment-393267147, was it this piece of code you tried changing?

https://github.com/web-platform-tests/wpt/blob/020e53ba4c7c35bbcfa80699d160b76c482880f2/tools/wptserve/wptserve/sslutils/openssl.py#L211

How do you run `_generate_ca()` to test out changes? Seems like it's only called implicitly, so you have to delete cacert.pem and then do... `./wpt serve`? I tried that and it doesn't work :)

**Comment by jgraham** [comment] 2018-09-25 10:31
I think you need to set the ssl type to `openssl` in the `config.json` file.

**Comment by jgraham** [comment] 2018-09-25 10:32
And yes, that's the code I tried changing.

**Closed** 2018-12-20 14:19 UTC
Labels: infra, priority:roadmap
