### ISSUE TITLE
Stop running wpt-chrome-dev-stability for Chromium exports

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#29737] opened 2021-07-21 16:04 UTC
The value of running wpt-chrome-dev-stability for Chromium exports is very low, and when it fails we (the Chromium team) almost always ignore. Let's not run it for PRs created by the wpt export bot.

**Comment by jgraham** [comment] 2021-07-23 19:55
I wouldn't complain if you also did the same for Gecko exports and the Firefox run. Often that fails just because the build being used hasn't got the relevant patch.

**Comment by foolip** [comment] 2021-07-23 20:32
@jgraham the way I imagine this working is based on the commit message. For Chromium exports it would probably be "Cr-Commit-Position" in the commit message, and for Gecko maybe "gecko-commit"?

We could also use the committer, which is blink-w3c-test-autoroller@chromium.org and wptsync@mozilla.com respectively.

There are already some triggers based on the commit message, right?

**Comment by foolip** [comment] 2021-09-02 21:00
OK, so it looks like tools/ci/jobs.py doesn't look at commit messages at all. The `get_extra_jobs` method I recalled is in tools/ci/tc/decision.py. That's probably where I should change this.

**Comment by jgraham** [comment] 2021-09-03 08:59
Yeah, the split between jobs.py and the decision task probably doesn't make much sense now. It's likely easier to fix this in the decision task.

**Comment by DanielRyanSmith** [comment] 2021-12-05 01:44
Hello @foolip and @jgraham! I was taking a look at this earlier and I want to make sure I am understanding this correctly. 

From my understanding, we NEVER want to run `wpt-chrome-dev-stability` for PRs opened by @chromium-wpt-export-bot or @moz-wptsync-bot, is that true?
> I wouldn't complain if you also did the same for Gecko exports and the Firefox run

Maybe the Firefox run does not fall into this category and should be identified a different way?

I was looking at some PRs open by chromium-wpt-export-bot I saw [this PR](https://github.com/web-platform-tests/wpt/pull/31890) that does not contain "Cr-Commit-Position" in the commit or PR message, but `wpt-chrome-dev-stability` still runs. Maybe just ensuring any PRs open with the above usernames will avoid these test runs more assuredly?

[I created a possible draft of a solution](https://github.com/web-platform-tests/wpt/pull/31898/files). Does this look sufficient for fixing this issue?

**Comment by jgraham** [comment] 2021-12-05 17:54
That's not quite right. For Chrome exports we don't want to run `wpt-chrome-dev-stability` but do want to run `wpt-firefox-nightly-stability` (or whatever the job names are), for Firefox exports we do want to run the Chrome stability job, but don't want to run the Firefox stability job (the idea is basically that if we already merged the changes into a vendor repo there's no benefit in running the stability checks in that browser, since they are already running the tests, and there's often a situation where the patch adding or updating tests also has browser changes which make the test stable, but which aren't yet in a build we can use at the point the PR is opened).

**Comment by DanielRyanSmith** [comment] 2021-12-05 18:41
I see. So then the only change in the logic would be to instead ignore `wpt-firefox-nightly-stability` for PRs opened by @moz-wptsync-bot then instead of `wpt-chrome-dev-stability`, yes?

**Comment by foolip** [comment] 2021-12-07 08:57
@DanielRyanSmith can you check that this is in fact working now and reopen this issue if not?

**Comment by DanielRyanSmith** [comment] 2021-12-07 18:41
Yeah, based on some of the new exports [like this one](https://github.com/web-platform-tests/wpt/pull/31935), it looks like the stability tests are not being excluded still. I have to guess this is because the commits are actually co-authored by the user and the bot. I'll try and find a fix.

**Comment by DanielRyanSmith** [comment] 2021-12-07 20:32
It's a little tough to thoroughly test this without being to open PRs directly as the bot account, but I believe I identified the issue. I was accessing the username of the most recent action in the PR rather then the original opener of the PR. [This change should hopefully fix this.](https://github.com/web-platform-tests/wpt/pull/31941)

**Comment by foolip** [comment] 2021-12-08 17:09
Alright, that's merged now! A future Chromium or Gecko export PR should reveal if it now works.

**Comment by DanielRyanSmith** [comment] 2021-12-08 22:26
Okay, so this was a needed change, but it did not work in the export PRs. After some tinkering, I realized that the task are definitively chosen in a separate function and the filtering needs to occur there. I hijacked [this export PR](https://github.com/web-platform-tests/wpt/pull/31963) to make absolutely sure my changes worked this time, and it seems it was the case.

[Here is (hopefully) the final PR to finish this](https://github.com/web-platform-tests/wpt/pull/31966) 😅 

Thanks for being patient as I get used to the infrastructure 🙂

**Comment by DanielRyanSmith** [comment] 2021-12-13 09:46
It looks like the stability tests are being excluded as intended for the PRs from @chromium-wpt-export-bot. I will tentatively close this issue for now.

**Closed** 2021-12-13 09:46 UTC
Labels: infra

**Comment by foolip** [comment] 2021-12-13 11:40
Indeed, https://github.com/web-platform-tests/wpt/pull/32027 looks good. Thanks @DanielRyanSmith!

Unfortunately there's no gecko sync recent enough to include https://github.com/web-platform-tests/wpt/pull/31966 so I can't see if that's working or not.
