### ISSUE TITLE
Consider using Chrome’s new Headless mode (`--headless=new` instead of just `--headless`)

### ISSUE THREAD

**Issue by mathiasbynens** [web-platform-tests/wpt#40856] opened 2023-07-03 11:16 UTC
Technically, the old Headless was a separate, alternate browser implementation that happened to be shipped as part of the same Chrome binary. The new Headless is what users might expect — an invisible mode of the real Chrome browser.

More info: https://developer.chrome.com/articles/new-headless/

It might be worth switching to `--headless=new` instead of `--headless` for improved accuracy in wpt.fyi test results.

**Comment by mathiasbynens** [comment] 2023-07-03 11:18
cc @DanielRyanSmith

**Comment by OrKoN** [comment] 2023-07-03 11:18
One example of the difference is how the page visibility is handled: in the old headless, `document.hidden` is false even if the tab is in the background.

**Comment by DanielRyanSmith** [comment] 2023-07-04 03:40
I am not certain of the work involved to implement here (hopefully not much), but I do agree that the new headless mode is definitely a great use case for WPT. We're not using the old headless mode for the reasons you mentioned @mathiasbynens. When I saw the new headless functionality, WPT was the first thing that came to mind, and I spoke about it to Peter informally. It would be great to make the switch!

**Comment by rakuco** [comment] 2023-09-15 11:05
> One example of the difference is how the page visibility is handled: in the old headless, `document.hidden` is false even if the tab is in the background.

I was excited about this as well, but some quick testing with making wptrunner pass `--headless=new` did not work either. Having this working would be great for `page-visibility/` web tests as well as other tests in WPT that rely on `page-visibility/resources/window_state_context.js`.

I also see a couple of workarounds for old-headless in the ChromeDriver code base that either need to be removed in the future or adapted to also cover new-headless.

@mathiasbynens @DanielRyanSmith What's the best way to help? Is there a tracking bug on the Chromium side? Should old bugs like https://bugs.chromium.org/p/chromium/issues/detail?id=1038050 be reused for the new headless mode?

**Comment by OrKoN** [comment] 2023-09-15 12:08
@rakuco that seems to work for webdriver bidi wpt tests https://github.com/web-platform-tests/wpt/blob/master/webdriver/tests/bidi/browsing_context/activate/activate.py (we test the page visibility change using browsingContext.activate). I guess we could re-use existing bugs but I will also work if we file new issues specifically for the new headless with specific reproduction steps.

**Comment by rakuco** [comment] 2023-09-22 12:14
> @rakuco that seems to work for webdriver bidi wpt tests https://github.com/web-platform-tests/wpt/blob/master/webdriver/tests/bidi/browsing_context/activate/activate.py (we test the page visibility change using browsingContext.activate).

Those tests don't seem to change the window state as far as I can see, so I think the minimize/maximize bits remain untested there.

> I guess we could re-use existing bugs but it will also work if we file new issues specifically for the new headless with specific reproduction steps.

I've filed https://crbug.com/1485918 as a tracking bug for everything that needs to be done on the Chromium side for --headless=new to work. https://crbug.com/1485920 tracks the lack of minimize/maximize support on Linux, with reproduction steps that only require a Chromium checkout.

**Comment by OrKoN** [comment] 2023-09-22 12:18
@rakuco to clarify: I meant that you can test page visibility by using browsingContext.activate in the new headless. I am not sure it makes sense to test this using window management in the headless environment because UI windows are not shown. I will defer to kvitekp@ for the decision on whether window managament could be be supported in the new headless. Separate bugs to track this make sense because the implementation of the old and new headless are different.

**Comment by rakuco** [comment] 2023-09-22 12:25
Thanks! _Some_ form of support is quite important IMO, as the current situation where ChromeDriver commands like `minimize` just fail cause several tests in WPT that depend on page visibility not to work in headless mode (and, from a downstream perspective, it means the same tests will fail in Chromium CI once tests in WPT are run via run_wpt_tests.py instead of run_web_tests.py).

**Comment by rakuco** [comment] 2024-01-02 14:29
Some page visibility issues have been fixed in Chromium in the past few months, I wonder what the next steps are here: has anyone tried comparing the results for a full run with old headless mode vs new headless mode?

**Comment by fergald** [comment] 2024-01-11 06:40
FYI old headless mode is incompatible with BFCache and possibly preloading too. All tests that expect BFCaching to occur result int PRECONDITION_FAILED on the old headless.

**Comment by WeizhongX** [comment] 2024-01-12 17:53
@mathiasbynens do you know if `--headless=new` works in chrome android and WebView?

**Comment by past** [comment] 2024-02-02 19:31
Fixed by #44304.

**Closed by past** 2024-02-02 19:31 UTC
Labels: infra
