### ISSUE TITLE
Infrastructure needs for testing Periodic Background Sync API

### ISSUE THREAD

**Issue by mugdhalakhani** [web-platform-tests/wpt#20215] opened 2019-11-12 17:49 UTC
Periodic Background Sync (https://github.com/WICG/BackgroundSync/blob/master/explainers/periodicsync-explainer.md) has been in Origin Trial since Chrome 77.

In order to enable creating a shared test suite for the API, additional testing infrastructure would be necessary for the following non-comprehensive list of items:

- Influencing the status of the permission required by the feature: Not having this prevents most testing since register() rejects unless periodic-background-sync permission is granted.
- Providing a test clock which can artificially forward elapsed time: This will enable us to verify that the browser ensures a minimum interval of 'minInterval' between periodicsync events.

**Comment by stephenmcgruer** [comment] 2019-11-20 14:07
@LukeZielinski will the first of these bullet points be addressed with the work you're doing on the Permissions API in testdriver?

**Comment by LukeZielinski** [comment] 2019-11-20 15:10
Sounds like it will, yes, since we can use the SetPermission API to grant the `periodic-background-sync` permission.

**Comment by mugdhalakhani** [comment] 2019-11-20 15:54
Can you please point me to existing WPT tests that use it?

**Comment by LukeZielinski** [comment] 2019-11-20 17:11
None yet, but I'll add an infra test as part of fixing https://github.com/web-platform-tests/wpt/issues/5671

**Comment by mugdhalakhani** [comment] 2019-11-20 17:32
Thanks. I've added myself to the watchlist for that Issue.

**Comment by LukeZielinski** [comment] 2019-12-03 20:47
For posterity, permissions API was added to testdriver in https://github.com/web-platform-tests/wpt/pull/20461

**Comment by stephenmcgruer** [comment] 2019-12-04 19:45
So the remaining ask is then:

> Providing a test clock which can artificially forward elapsed time: This will enable us to verify that the browser ensures a minimum interval of 'minInterval' between periodicsync events.

Do you know if we've had previous requests for this functionality @LukeZielinski ? It seems like a trivial (he says) and suitable (he says) webdriver API to me.

**Comment by mugdhalakhani** [comment] 2019-12-05 13:45
> For posterity, permissions API was added to testdriver in #20461
Thanks @LukeZielinski, I'm guessing this is yet to be rolled up to Chromium code?
https://cs.chromium.org/chromium/src/third_party/blink/web_tests/external/wpt/infrastructure/testdriver/set_permission-expected.txt suggests so, and I get:
promise_test: Unhandled rejection with value: object "Error: unimplemented"\n
when trying to use it as:
return test_driver.set_permission("periodic-background-sync", "granted");

**Comment by LukeZielinski** [comment] 2019-12-05 20:03
@stephenmcgruer First time I'm coming across the request for a test clock. But it sounds like you'd want to advance a clock inside Chrome itself in order to cause it to trigger another event, right? Which means you'd still need to implement the whole path of testdriver->webdriver->chromedriver->devtools->chrome (as described in our [automation doc](https://docs.google.com/document/d/18BpD41vyX1cFZ77CE0a_DJYlGpdvyLlx3pwXVRxUzvI/edit#)). So I agree that it's probably suitable, but not exactly trivial.

@mugdhalakhani Correct, we still need to do more work to get Chromium's version of testdriver to support this command. It's tracked in [crbug.com/1030663](http://crbug.com/1030663). But in the mean time, you can use WPT's testdriver to unblock test development (if possible).

**Comment by stephenmcgruer** [comment] 2020-03-26 22:45
Looks like with the permissions API fixed, this is now a dupe of https://github.com/web-platform-tests/wpt/issues/17489 ?

**Closed** 2021-01-26 12:15 UTC
Labels: infra, priority:backlog, testdriver.js, type:untestable
