### ISSUE TITLE
Annotating tests for optional features

### ISSUE THREAD

**Issue by jugglinmike** [web-platform-tests/wpt#12766] opened 2018-08-30 19:23 UTC
It's currently difficult to contribute tests for functionality that is specified as optional. (See gh-12732 for a recent example.)

In some cases, test authors can wrap their sub-tests tests in feature-detection logic so that they are only executed in browsers that advertise support. This results in "empty" tests for non-supporting browsers, and that's not ideal because it complicates the meaning of cross-browser comparisons. Worse, [this approach isn't always an option because support cannot be detected.](https://github.com/web-platform-tests/wpt/pull/10840)

Authors could simply write the test as if the feature was mandatory. Consumers generally are able to allow test failures, so they can tolerate tests that they do not intend to satisfy. That's a bit of a hassle, though, since consumers will need to triage the relevance of each new failure whenever they update WPT.  People outside of the browser projects don't necessarily have access to these lists, so they'll be on their own when it comes to interpreting failures.

A machine-readable annotation for these tests would allow implementers to explicitly opt-in on a case-by-case basis, and it would help others to interpret and compare test results.

[As @zcorpan points out](https://github.com/web-platform-tests/wpt/pull/12732#issuecomment-416956116), [the CSS test suite already supports this via the "may" flag](https://web-platform-tests.org/writing-tests/css-metadata.html). We might promote that to be used across all of WPT. However, it seems likely that consumers will implement some subset of optional behavior. If all optional tests were annotated generically, consumers would still have to pick through them on a case-by-case basis. They may be able to use the directory structure to automate this. Rules like "allow optional tests in ` html/semantics/embedded-content/media-elements` to fail" may be sufficient. It also might be too coarse. It might be better to support a rule like "allow optional tests for autoplay to fail." That would require additional metadata (specifying both that the feature is optional and a name for the optional feature), but I don't know enough about the prevalence of optional features to say if the trade-off is worth it.

**Comment by foolip** [comment] 2018-08-30 20:16
Another feature which has been frustrating testing-wise is [`<video preload>`](https://html.spec.whatwg.org/multipage/media.html#attr-media-preload). It is merely a hint, even for `preload=none`, see "Optionally, run the following substeps" in the [resource fetch algorithm](https://html.spec.whatwg.org/multipage/media.html#concept-media-load-resource).

@jugglinmike, I think you're right that merely marking tests as optional won't do much, each user of WPT would still need to look at each such test and decide whether they want to make it pass or not. However, I'm not sure how much optional tests could be grouped together to alleviate this problem.

FWIW, this is quite similar to the problem of dealing with tentative tests.

**Comment by zcorpan** [comment] 2018-08-31 06:56
If we mark optionalness on a per-file basis, I think a filename convention could be better than in-file metadata, since it's more visible (if you look at a list of tests being imported, for example).

**Comment by jgraham** [comment] 2018-08-31 15:42
The problem is that there are at least three classes of optionality:

* Things that are flagged as optional in specs, but in practice all browsers have to pick the same behaviour (some other class of UA might pick another behaviour, but we don't really care about that). 

* Things that are truely optional and each UA picks exactly one behaviour and always implements it.

* Things that are opttional and some or all UAs make the choice of which approach to take context dependent (e.g. `<video preload>` bevahiour could depend on the kind of network connection or other heuristics about the system performance).

So I don't think there's really a good solution here. For the first case we should just write tests as normal and just test whatever the browser-required behaviour is. For other cases if there's really no consensus on which approach to take, trying to share tests may not be very high value so no solution is needed (but implementors probably want to some way to write implementation-specific tests that looks like wpt tests so they can be promoted to wpt tests if a standard behaviour is adopted in the future).

**Comment by gsnedders** [comment] 2018-08-31 15:45
CSS also has a "should" flag, as well as "may" (corresponding to the RFC2119 states). It's been brought up before that having this metadata is a requirement for CSS WG implementation reports previously.

**Comment by jugglinmike** [comment] 2018-08-31 17:10
I'm in favor of the "do not test in WPT" answer; I just initially assumed this was a case of my being too conservative. It's what I recommended in gh-10840, but I lacked the confidence to insist on it. If we can get agreement from more maintainers, then we should document it as a formal policy.

@gnsedders @annevk @domenic @foolip you folks give a lot of reviews. What do you think about rejecting tests for optional behavior and recommending UAs maintain their own tests instead? Do you think we can/should have a more nuanced rule that allows tests which are practically mandatory (e.g. [tests which interact with caches](https://github.com/web-platform-tests/wpt/issues/12763))?

**Comment by jugglinmike** [comment] 2018-08-31 17:11
My mistake: I meant "@gsnedders"

**Comment by domenic** [comment] 2018-08-31 17:17
I'd prefer UAs being able to share tests, at least in cases where there might conceivably be shared behavior. In several cases I think we've committed "should" tests where most or all browsers passed them.

**Comment by jugglinmike** [comment] 2018-09-05 01:44
@domenic I could be convinced that the benefit of shared tests outweighs the drawbacks of irrelevant failures. I'm most interested in consistency. If we want to accept "most" tests, do you think there's an objective heuristic we could use?

**Comment by domenic** [comment] 2018-09-05 02:00
Perhaps if a test is useful by 2+ engines

**Comment by foolip** [comment] 2018-10-17 21:17
Concrete proposal: a `.optional.` test name flag similar to [`.tentative.`](https://web-platform-tests.org/writing-tests/file-names.html) which can be used for the explicitly-optional-in-spec case, and nothing else until we find a reason to cover other cases. It should be obvious from the test what the behavior under test is, with a comment or spec link.

**Closed** 2018-10-19 09:03 UTC
Labels: policy
