### ISSUE TITLE
Get all infra working on Python 3

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#8820] opened 2017-12-30 00:49 UTC
We probably want to split these out into individual issues, but given I don't think we're doing this any time soon I'll leave that for when someone starts on this:

- [ ] ci
- [ ] gitignore
- [ ] lint
- [ ] manifest
- [ ] runner
- [ ] serve
- [ ] sslutils
- [ ] webdriver
- [ ] wpt
- [ ] wptrunner
- [ ] wptserve

Note that even after updating all of this we'll still rely on Python 2 as we have hundreds of helper files for tests.

**Comment by jugglinmike** [comment] 2019-02-14 20:36
See gh-10128 for wptrunner

**Comment by jayvdb** [comment] 2019-03-27 13:17
I see that some of these sdists do not have tests included.

It will be much easier for packagers to do tests on Python 3 if the sdist for each has the tests included.

**Comment by jgraham** [comment] 2019-03-27 15:32
The PyPI packages are in general not actively maintained (although speserve is sometimes updated) and aren't actually used by any wpt infrastructure or by browser vendors who import this stuff (afaik).

**Comment by jayvdb** [comment] 2019-03-27 15:33
I ran into them because http://pypi.org/project/mozfile is using `wptserve` in its test rig.

**Comment by jayvdb** [comment] 2019-03-28 07:17
You can tick `manifest`.

https://build.opensuse.org/package/show/home:jayvdb:wpt/python-wptmanifest

`test_manifest_to_json` is failing a lot, mostly because the test case generation is too slow.  I've disabled that test on all platforms atm.

`test_manifest_idempotent` is also failing most of the time on arm arch, for the same reason.

I note that http://pypi.org/project/manifest/ was pre-alpha, and now redundant, and the author would probably be willing to release the name to wpt project.

`mod_pywebsocket` on PyPI (0.79) has Python 2 only code in it, and upstream master. https://github.com/google/pywebsocket/issues/153 .  Note they also have test failures on Python 2. https://github.com/google/pywebsocket/issues/154  And I see the local copy here is *heavily* modified, so getting those changes merged upstream could be quite a bit of work.  And when I try running the test suite with the locally modified version of `mod_pywebsocket`, it halts https://build.opensuse.org/package/live_build_log/home:jayvdb:wpt/python-mod_pywebsocket/openSUSE_Tumbleweed/x86_64 , and the test suite for wptserve also halts https://build.opensuse.org/package/live_build_log/home:jayvdb:wpt/python-wptserve/openSUSE_Leap_15.1/x86_64

`mod_pywebsocket` is used by `serve.py`, which is needed by at least `wptserve` for testing, so fixing `mod_pywebsocket` is a high priority, otherwise we cant run the tests properly.

**Comment by foolip** [comment] 2019-09-10 08:34
I spotted the [Moving to Python 3](https://lists.webkit.org/pipermail/webkit-dev/2019-July/thread.html#30724) thread on webkit-dev. Key quote:
> Now that the Catalina developer seeds are available, it is official that the new Mac developer tools come with Python 3.

There was discussion on the thread about running on older versions of macOS that don't have Python 3, and if WPT's Python code is used in any way in WebKit that concern can translate.

But in any case, sounds like we could soon start thinking about using Python 3 on macOS as well. Even today we could install Python 3 on Azure Pipelines of course, but the hard question is whether we keep it working with Python 2.

@youennf @rniwa is there any impact of WPT's Python code on WebKit? Would it be good for WebKit is WPT supports Python 3, or does it not matter?

**Comment by rniwa** [comment] 2019-09-10 09:36
> @youennf @rniwa is there any impact of WPT's Python code on WebKit? Would it be good for WebKit is WPT supports Python 3, or does it not matter?

As things stand, we won't be able to run imported tests if WPT tests relied upon Python3 since older versions of macOS on which we still run regression (layout) tests do not support Python3 by default.

**Comment by foolip** [comment] 2019-09-10 10:42
Does that include only wptserve and the "CGI" .py files that are written as part of tests, or do you also rely on other parts of WPT to work using Python 2?

**Comment by gsnedders** [comment] 2019-09-10 17:12
> You can tick manifest, as its tests pass on py3.

Alas, it… doesn't actually work. :flushed: There's a huge diff between manifests generated by Python 2 and Python 3.

**Comment by Hexcles** [comment] 2019-09-19 02:53
TPAC discussions:
https://www.w3.org/2019/09/16-testing-minutes.html#item05
https://www.w3.org/2019/09/16-testing-minutes.html#item07

**Comment by jayvdb** [comment] 2019-09-19 05:17
> There's a huge diff between manifests generated by Python 2 and Python 3.

Interesting!  It sounds like there should be some regression tests which compares the generated results to expected results generated from python2.

**Comment by gsnedders** [comment] 2019-10-04 15:52
@jayvdb Yeah, we should, just never got around to writing one because it's so far from passing (and it never has). Can't regress something that never worked. :)

**Comment by Ms2ger** [comment] 2019-11-05 10:17
CC @ericlaw1979; help is welcome.

**Comment by ExE-Boss** [comment] 2020-03-16 17:58
`wpt serve` runs fine in **Python 3** on **Windows**.

**Comment by foolip** [comment] 2021-05-06 14:54
This is done, we are now Python 3 only!

**Comment by foolip** [comment] 2021-05-06 14:54
https://github.com/web-platform-tests/wpt/issues/28776 tracks some additional cleanup.

**Closed by foolip** 2021-05-06 14:54 UTC
Labels: infra, priority:backlog
