### ISSUE TITLE
Safari TP is not showing results for url-constructor.html on wpt.fyi

### ISSUE THREAD

**Issue by domenic** [web-platform-tests/wpt#18360] opened 2019-08-09 20:52 UTC
http://web-platform-tests.live/url/url-constructor.html runs fine on my local Safari Tech Preview. It does not show on https://wpt.fyi/results/url/url-constructor.html?label=master&label=experimental, however. Even if I change the SHA manually to point to various other commits, nothing shows up.

**Comment by Hexcles** [comment] 2019-08-09 21:01
I can't find any recent run where Safari (stable or experimental) even runs that test
https://wpt.fyi/results/?label=master&label=stable&max-count=10&product=safari&q=url%2Furl-constructor.html%2B%2Bsafari%3Aok

In fact, a lot of tests under url/ never seem to run on Safari on Azure Pipelines. If those tests can run just fine locally, then we might have some setup issue.

**Comment by foolip** [comment] 2019-08-10 07:46
This could be an instance of https://github.com/web-platform-tests/wpt/issues/16229. To know for sure, we'd have to figure out which chunk this test should be in and check if that chunk always exits early.

**Comment by foolip** [comment] 2019-08-19 09:47
https://wpt.fyi/results/url/url-constructor.html?run_id=280980002 has results from https://github.com/web-platform-tests/wpt/pull/18519 where I tried increasing the number of jobs. That confirms that the problem is not with the test itself, but rather all the tests aren't being run currently. Closing as a dupe of https://github.com/web-platform-tests/wpt/issues/16229.

**Closed by foolip** 2019-08-19 09:48 UTC
Labels: Azure Pipelines, infra, url

**Comment by foolip** [comment] 2019-08-23 11:15
A workaround has been landed and the latest aligned run now has results for Safari TP as well:
https://wpt.fyi/results/url/url-constructor.html?run_id=281080007&run_id=276860005&run_id=289180009&run_id=276860007

Searching for `chrome:pass firefox:pass safari:!pass` and `chrome:!pass firefox:!pass safari:pass` lists some tests that might be interesting from an interop POV.
