### ISSUE TITLE
`tools/wpt/tests/test_wpt.py` integration tests failing because Chrome fails to start

### ISSUE THREAD

**Issue by jonathan-j-lee** [web-platform-tests/wpt#42433] opened 2023-10-09 19:26 UTC
[`test_run_failing_test` and `test_run_verify_unstable` fail](https://github.com/web-platform-tests/wpt/runs/17538354562) with a log like:

```
 2:47.16 pid:8087 Full command: /Users/runner/work/1/s/_venv3/bin/chrome/chromedriver --port=51052 --url-base=/ --enable-chrome-logs --disable-build-check
pid:8087 Starting ChromeDriver 118.0.5993.3 (7a51b9ea23325fae1ec1dad5a02c67c2240d7b11-refs/branch-heads/5993@{#7}) on port 51052
 2:47.16 pid:8087 Only local connections are allowed.
 2:47.16 pid:8087 Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
 2:47.16 pid:8087 ChromeDriver was started successfully.
 2:47.87 pid:8087 [8094:259:1009/190056.835364:WARNING:chrome_main_delegate.cc(660)] This is Chrome version 120.0.6051.2 (not a warning)
 2:48.15 pid:8087 [8094:259:1009/190057.109992:INFO:policy_logger.cc(145)] :components/enterprise/browser/controller/chrome_browser_cloud_management_controller.cc(168) Starting CBCM Controller Initialization
 2:48.15 pid:8087 [8094:259:1009/190057.110115:INFO:policy_logger.cc(145)] :components/enterprise/browser/controller/chrome_browser_cloud_management_controller.cc(196) No machine level policy manager exists.
 2:48.31 pid:8087 
 2:48.31 pid:8087 DevTools listening on ws://127.0.0.1:51132/devtools/browser/8c8e5c27-9230-4025-ac55-695dec793e42
 2:49.79 pid:8087 [1696878058.760][WARNING]: You are using an unsupported command-line switch: --disable-build-check. Please don't report bugs that cannot be reproduced with this switch removed.
 2:50.05 WARNING Protocol.setup caught an exception:
Post-connection steps failed
Traceback (most recent call last):
  File "/Users/runner/work/1/s/tools/wptrunner/wptrunner/executors/protocol.py", line 71, in setup
    self.after_connect()
  File "/Users/runner/work/1/s/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 475, in after_connect
    self.testharness.load_runner(self.executor.last_environment["protocol"])
  File "/Users/runner/work/1/s/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 120, in load_runner
    self.parent.base.execute_script(self.runner_script % format_map)
  File "/Users/runner/work/1/s/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 55, in execute_script
    return method(script)
  File "/Users/runner/work/1/s/tools/webdriver/webdriver/client.py", line 22, in inner
    return func(self, *args, **kwargs)
  File "/Users/runner/work/1/s/tools/webdriver/webdriver/client.py", line 779, in execute_script
    return self.send_session_command("POST", "execute/sync", body)
  File "/Users/runner/work/1/s/tools/webdriver/webdriver/client.py", line 658, in send_session_command
    return self.send_command(method, url, body, timeout)
  File "/Users/runner/work/1/s/tools/webdriver/webdriver/client.py", line 622, in send_command
    raise err
webdriver.error.UnknownErrorException: unknown error (500): unknown error: result.webdriverValue.value list is missing or empty in Runtime.callFunctionOn response
  (Session info: chrome=120.0.6051.2)

Remote-end stacktrace:

0   chromedriver                        0x000000010b377528 chromedriver + 4957480
1   chromedriver                        0x000000010b36ec23 chromedriver + 4922403
2   chromedriver                        0x000000010af20e07 chromedriver + 409095
3   chromedriver                        0x000000010af26bbc chromedriver + 433084
4   chromedriver                        0x000000010af29580 chromedriver + 443776
5   chromedriver                        0x000000010afb39bb chromedriver + 1010107
6   chromedriver                        0x000000010af96e82 chromedriver + 892546
7   chromedriver                        0x000000010afb2fa1 chromedriver + 1007521
8   chromedriver                        0x000000010af96c53 chromedriver + 891987
9   chromedriver                        0x000000010af61879 chromedriver + 673913
10  chromedriver                        0x000000010af62aae chromedriver + 678574
11  chromedriver                        0x000000010b339869 chromedriver + 4704361
12  chromedriver                        0x000000010b33e2f8 chromedriver + 4723448
13  chromedriver                        0x000000010b33e8a5 chromedriver + 4724901
14  chromedriver                        0x000000010b344f6e chromedriver + 4751214
15  chromedriver                        0x000000010b33eeed chromedriver + 4726509
16  chromedriver                        0x000000010b31479f chromedriver + 4552607
17  chromedriver                        0x000000010b35d968 chromedriver + 4852072
18  chromedriver                        0x000000010b35db20 chromedriver + 4852512
19  chromedriver                        0x000000010b36e85e chromedriver + 4921438
20  libsystem_pthread.dylib             0x00007ff806b1d1d3 _pthread_start + 125
21  libsystem_pthread.dylib             0x00007ff806b18bd3 thread_start + 15


 2:50.09 pid:8087 [8094:259:1009/190059.052825:ERROR:network_service_instance_impl.cc(615)] Network service crashed, restarting service.
 2:50.09 pid:8087 [8094:259:1009/190059.058449:ERROR:gpu_process_host.cc(990)] GPU process exited unexpectedly: exit_code=15
 2:50.09 pid:8087 [8094:259:1009/190059.059056:WARNING:gpu_process_host.cc(1360)] The GPU process has crashed 1 time(s)
 2:50.16 pid:8087 [8094:259:1009/190059.127384:WARNING:sad_tab.cc(255)] Tab Killed: http://web-platform.test:8000/
 2:50.28 pid:8087 [8094:259:1009/190059.249850:WARNING:gpu_process_host.cc(1013)] Reinitialized the GPU process after a crash. The reported initialization time was 77 ms
 2:50.48 pid:8087 [8094:259:1009/190059.444009:WARNING:pref_notifier_impl.cc(41)] Pref observer for media_router.cast_allow_all_ips found at shutdown.
```

[The test passed today](https://github.com/web-platform-tests/wpt/pull/42413/checks?check_run_id=17538822905) after replacing `--channel=dev` with `--install-browser --channel=stable` in those tests, so a new Chrome/chromedriver version likely caused the regression. Searching for the error message, I found https://crrev.com/c/4889644, which changes the error message recently and looks at least somewhat relevant.

Tentatively assigning that CL's author to investigate.

CC @nechaev-chromium

**Comment by past** [comment] 2023-10-09 21:29
CC @sadym-chromium, @thiagowfx

**Comment by nechaev-chromium** [comment] 2023-10-11 15:28
118.0.5993.3 is an old Beta that has this problem.
Try using a newer version e.g. 118.0.5993.70.
The problem is fixed there.

**Comment by past** [comment] 2023-10-31 21:40
This has been now fixed, but please reopen if I am mistaken.

**Closed by past** 2023-10-31 21:40 UTC
Labels: infra, wpt
