### ISSUE TITLE
Usage of is="" attribute in helpers for CEReactions tests

### ISSUE THREAD

**Issue by clopez** [web-platform-tests/wpt#21854] opened 2020-02-18 13:29 UTC
The helper functions for CEReactions added in f7086960db8 and ce667da7c2c are using the `is=""` attribute for the tests.

Apple WebKit developers have stated that they won't implement support for that attribute. See: https://bugs.webkit.org/show_bug.cgi?id=182671

That its causing failures on Safari and WebKitGTK on the following WPT tests:

```
$ git grep -lP '(testReflectAttributeWithParentNode|testReflectBooleanAttributeWithParentNode|testReflectAttributeWithDependentAttributes|testReflectBooleanAttributeWithDependentAttributes)'|grep html
custom-elements/reactions/HTMLAreaElement.html
custom-elements/reactions/HTMLBaseElement.html
custom-elements/reactions/HTMLButtonElement.html
custom-elements/reactions/HTMLFieldSetElement.html
custom-elements/reactions/HTMLImageElement.html
custom-elements/reactions/HTMLLIElement.html
custom-elements/reactions/HTMLLabelElement.html
custom-elements/reactions/HTMLMediaElement.html
custom-elements/reactions/HTMLMetaElement.html
custom-elements/reactions/HTMLMeterElement.html
custom-elements/reactions/HTMLOptGroupElement.html
custom-elements/reactions/HTMLParamElement.html
custom-elements/reactions/HTMLStyleElement.html
custom-elements/reactions/HTMLTableCellElement.html
custom-elements/reactions/HTMLTableColElement.html
```

On top of that on 98103d8c3ec ```testReflectAttribute``` and ```testReflectAttributeWithContentValues``` helpers were modified to optionally also use the is="" attribute

I wonder if it would be possible and a good idea to rewrite this helpers functions to not use the `is=""` attribute?
Or if we should expect this tests to fail on Safari and WebKitGTK because supporting `is=""` is needed for this tests?

//cc @rniwa @xiaoyu3x @kaixinjxq  @domenic 

Related: #5727

**Comment by domenic** [comment] 2020-02-18 13:32
> Or if we should expect this tests to fail on Safari and WebKitGTK because supporting is="" is needed for this tests?

This is correct.

**Comment by stephenmcgruer** [comment] 2020-02-18 18:41
If:

1. Supporting `is=""` is required for the tests to function (i.e. it is not just a convenience for the helper), but
1. The tests are not testing `is=""` support directly themselves, and
1. There is another test that tests for `is=""` support,

Then these tests could have an `assert_precondition` added for that support.

**Comment by domenic** [comment] 2020-02-18 18:44
(1) is true.

I'm unsure how to answer (2); they are testing reactions on customized built-in elements, and the only way to create a customized built-in element is with `is=""`.

I'm unsure on (3) also; there are probably some tests of `is=""` besides these, but they will be similarly testing features of customized built-in elements, so it's not clear whether we'd call these tests less primary than the other tests.

Regardless of the answers to the questions, an `assert_precondition` might be reasonable anyway?

**Comment by stephenmcgruer** [comment] 2020-02-18 18:45
Yeah, the line for `assert_precondition` is quite vague :). It can be a useful tool to hide 'noise', but sometimes a failure is perfectly reasonable too!

**Comment by stephenmcgruer** [comment] 2020-02-28 18:37
Taking another look at this.

Given 'the only way to create a customized built-in element is with `is=""`', then this is not a bug with the tests as far as I can see. That is, not supporting `is=""` is equivalent to not supporting customized built-in elements.

Assuming that holds, my suggestion is that this should be closed as WontFix, and the support should be tracked at https://bugs.webkit.org/show_bug.cgi?id=182671.

**Closed** 2020-05-01 20:36 UTC
