### ISSUE TITLE
Users without write access listed as "suggested reviewers"

### ISSUE THREAD

**Issue by jugglinmike** [web-platform-tests/wpt#13710] opened 2018-10-24 19:37 UTC
[The wpt-pr-bot](https://github.com/web-platform-tests/wpt-pr-bot) is currently reporting that some users referenced in WPT's `META.yml` file do not have write access to the repository. This means that their approval will now allow pull requests to be merged. These users should be removed from the lists.

**Comment by jugglinmike** [comment] 2018-10-25 19:37
<details>
  <summary>This Node.js script retrieves the repository's collaborators</summary>

```javascript
'use strict';

const octokit = require('@octokit/rest')();

const GITHUB_ACCESS_TOKEN = process.env.GITHUB_ACCESS_TOKEN;

if (!GITHUB_ACCESS_TOKEN) {
  console.error('Please set the GITHUB_ACCESS_TOKEN environment variable.');
  console.error('https://github.com/settings/tokens');
  process.exit(1);
}

octokit.authenticate({
  type: 'token',
  token: GITHUB_ACCESS_TOKEN
});

async function paginate (method, parameters) {
  let response = await method(parameters);
  const { data } = response;

  while (octokit.hasNextPage(response)) {
    response = await octokit.getNextPage(response);
    data.push(...response.data);
  }
  return data;
}

(async () => {
  const collaborators = await paginate(octokit.repos.getCollaborators, {
    owner: 'web-platform-tests',
    repo: 'wpt',
    // All collaborators with permissions to an organization-owned repository,
    // regardless of organization membership status.
    affiliation: 'all',
    per_page: 100,
    headers: {
      accept: 'application/vnd.github.hellcat-preview+json'
    }
  });

  console.log(
    collaborators
      .map((collaborator) => collaborator.login.toLowerCase())
      .sort()
      .join('\n')
  );
})();
```
</details>


<details>
  <summary>And this Python script retrieves all the GitHub handles listed as "suggested reviewers"</summary>

```python
import yaml
import os

reviewers = set()

for root, dirs, files in os.walk('.'):
    for file_name in files:
        if file_name != 'META.yml':
            continue

        with open(os.path.join(root, file_name)) as handle:
            contents = handle.read()

        reviewers |= set(yaml.load(contents)['suggested_reviewers'])

print '\n'.join(sorted(map(lambda name: name.lower(), reviewers)))
```

</details>

<details>
  <summary>Comparing the two results yields the following list:</summary>

- addyosmani
- alexshalamov
- aogilvie
- atanassov
- boggydigital
- bradkemper
- chaals
- chumpchief
- cptvitamin
- cvazac
- cwilso
- danielweck
- eric-carlson
- g-ortuno
- halindrome
- haoxli
- hillbrad
- jdashg
- joedow-42
- jonathankingston
- kenrussell
- klausw
- leonscroggins
- luser
- musingvirtual
- nikosandronikos
- odinho
- paulmeyer90
- rmcilroy
- robman
- simonsapin
- spanicker
- stuartparmenter
- summerlw
- tantek
- theres-waldo
- timvolodine
- titzer
- toji
- uysalere
- vr000m

</details>

That's not accurate, though. Some of the accounts in that list are definitely able to conduct reviews (e.g. [ewilligers](https://github.com/ewilligers)--see gh-8138). [GitHub defines "collaborators" with the following text](https://developer.github.com/v3/repos/collaborators/):

> For organization-owned repositories, the list of collaborators includes outside collaborators, organization members that are direct collaborators, organization members with access through team memberships, organization members with access through default organization permissions, and organization owners.

There's a further stipulation, though: "...[that] the authenticated user can see." I don't have administrative access to the wpt repository, so it might be that an admin would get better results after running the script. Even then, it may be that if a GitHub user has not made their membership public, then no one can verify it. That would make verifying the "suggested reviewers" kind of tough.

@foolip would you mind giving it a shot? Or giving me admin privileges?

**Comment by foolip** [comment] 2018-10-26 11:17
This is just a lack of tooling to keep things in sync, as we have no way of adding people to the org.

https://github.com/web-platform-tests/wpt/issues/11915 was a previous idea to fix this, but I didn't do anything since a GitHub API token would have to be available in Travis, and that's a broken model I don't want to keep spreading.

**Comment by foolip** [comment] 2018-10-26 11:18
https://github.com/web-platform-tests/wpt/issues/13702 is also relevant.

**Comment by foolip** [comment] 2018-10-26 11:35
I wrote some scripts for https://github.com/web-platform-tests/wpt/issues/11293 which should produce roughly the same lists as reported here. All who have had some activity in wpt in the past year I think we should just add to the reviewers team. The rest we should probably ping to see if they are even reachable by GitHub notifications.

**Comment by foolip** [comment] 2018-10-26 11:49
I can confirm that ewilligers is in the reviewers team like everyone else, nothing unusual. Indeed the explanation must be that org membership isn't public. (This also suggests that a bot to fix this problem would need admin rights, which isn't great.)

**Comment by foolip** [comment] 2018-10-30 14:48
<details>
<summary>Node script that gets all reviewer team members</summary>

```javascript
'use strict';

const octokit = require('@octokit/rest')();

const GH_TOKEN = process.env.GH_TOKEN;

if (!GH_TOKEN) {
  console.error('Please set the GH_TOKEN environment variable.');
  console.error('https://github.com/settings/tokens');
  process.exit(1);
}

octokit.authenticate({
  type: 'token',
  token: GH_TOKEN
});

async function paginate(method, parameters) {
  parameters = Object.assign({ per_page: 100 }, parameters);
  let response = await method(parameters);
  const { data } = response;

  while (octokit.hasNextPage(response)) {
    response = await octokit.getNextPage(response);
    data.push(...response.data);
  }
  return data;
}

(async () => {
  const teams = await paginate(octokit.orgs.getTeams, {
    org: 'web-platform-tests',
  });

  const reviewersTeam = teams.find(team => team.name === 'reviewers');

  const reviewers = await paginate(octokit.orgs.getTeamMembers, {
    team_id: reviewersTeam.id,
  });

  for (const r of reviewers) {
    console.log(r.login);
  }
})();
```
</details>

It list 249 usernames, which is the correct number.

**Comment by foolip** [comment] 2018-10-30 16:15
249 is now not the right number, as I've gone ahead and added all suggested reviewers to the reviewers mean, one by one manually.

There remain 5 users with invites to the org+team which means that the correspondence isn't perfect still.

**Comment by foolip** [comment] 2018-10-30 16:16
There are also 46 people in the reviewers team who aren't listed as a suggested reviewer in any directory.

Next I'll write a script to check for activity over the past N months, to see if it makes sense to remove inactive people from the reviewers team.

**Comment by foolip** [comment] 2019-01-25 16:47
I'm going to downgrade the priority of this one. It'll keep being confusing from time to time, but easy to fix in every individual case it happens.

**Comment by foolip** [comment] 2019-10-08 16:03
I won't be doing any more work on this, unassigning.

**Comment by foolip** [comment] 2019-10-08 16:08
Actually, closing in favor of https://github.com/web-platform-tests/wpt/issues/11915, which would be the fix for this.

**Closed by foolip** 2019-10-08 16:08 UTC
Labels: infra, priority:backlog
