### ISSUE TITLE
https://w3c-test.org/ is broken

### ISSUE THREAD

**Issue by alastor0325** [web-platform-tests/wpt#27282] opened 2021-01-22 02:51 UTC
STR.
1. go to https://w3c-test.org/

Expected.
2. it works

Actual.
2. unable to connect to the site

**Comment by sideshowbarker** [comment] 2021-01-22 08:10
Fixed now — thanks for taking time to report this

(For the record here, the cause was related to the switch to Python 3.7; we needed to do:

    setcap cap_net_bind_service=eip /usr/bin/python3.7

**Closed by sideshowbarker** 2021-01-22 08:10 UTC
