### ISSUE TITLE
Suppress Marionette debug/trace messages for wdspec tests

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt#12166] opened 2018-07-24 17:46 UTC
Recently Firefox jobs on Travis started to print a *lot* of Marionette debug messages (for every single DOM event and script loading, etc.), presumably due to some recent changes in Marionette itself. I've seen many cases where the log exceeds 32MB and gets truncated as a result. We should probably suppress these messages. cc @jgraham

**Comment by Hexcles** [comment] 2018-07-24 19:21
The problem seems to be worse than I thought. It can easily block PRs from landing in the following failure mode:

Affected tests use a lot of DOM events and/or script loading. Although the tests don't take too long to run, they produce a huge amount of log because of this issue. Once the log reaches 32MB, the output is disabled; and if the job cannot finish within the next 10 minutes, the job will be killed by Travis because of "no output".

Example: https://travis-ci.org/web-platform-tests/wpt/jobs/407504544

**Comment by Hexcles** [comment] 2018-07-27 14:21
Another example today: #12179

**Comment by Hexcles** [comment] 2018-07-27 20:56
This looks like a regression of Marionette.

Geckodriver doc says the default logging level is info (https://github.com/mozilla/geckodriver#log-object). And I also tried explicitly setting `moz:firefoxOptions.log.level`, but I still see a lot of "Marionette      DEBUG" messages from Firefox processes, which wasn't the case before.

cc @jgraham @whimboo

**Comment by whimboo** [comment] 2018-07-30 08:04
I assume the invocation of wpt runner somehow sets the `--webdriver-arg` argument to `-v` or even `-vv`? Nothing has been changed for logging recently.

Maybe it's a result of upgrading geckodriver from about a week ago? But even in the last releases which all were part this upgrade we didn't change anything related to this.

**Comment by Hexcles** [comment] 2018-07-30 15:51
A quick grep doesn't find any place that sets `--webdriver-arg` in stability checks. Maybe @jgraham would know more.

**Comment by whimboo** [comment] 2018-07-30 18:36
Do we store those logs somewhere? I would like to have at least a look at those. If not, maybe you can upload an excerpt?

**Comment by Hexcles** [comment] 2018-07-30 18:50
@whimboo there's a link to an example at the top.

**Comment by jgraham** [comment] 2018-07-31 18:01
@andreastt This is the issue with marionette having too-verbose logging.

**Comment by andreastt** [comment] 2018-07-31 18:07
This is not a regression, since it was a conscious decision to enable finer output from Marionette specifically for the wdspec tests. This is useful to developers when diagnosing why wdspec tests fail at Mozilla.

Since Travis does not support artifacts, a reasonable compromise here might be to decrease the log details on there. This is possible by setting the `marionette.log.level` pref (or, in this case, making sure it _is not_ being set by way of `--webdriver-arg '-vv'`).

**Comment by whimboo** [comment] 2018-08-01 08:40
Also I want to add that we still have `info` logging as default for Marionette. `trace` level logging for wdspec jobs was only added AFAIR to our CI system (https://bugzilla.mozilla.org/show_bug.cgi?id=1443446).

Whereby I can also see it when running the wdspec jobs locally with `mach`. So there must be something else too.

**Comment by whimboo** [comment] 2018-08-01 08:42
Well, please scratch the second half of my last comment. The alias I have actually uses `--webdriver-arg=-vv`.

**Comment by mdittmer** [comment] 2018-08-06 17:24
Ping @whimboo and @Hexcles. Is this issue ongoing in Travis land?

**Comment by whimboo** [comment] 2018-08-08 08:30
I think so. But to further help you I would need some links to see how the tests are started, including which arguments are used.

**Comment by foolip** [comment] 2018-08-10 11:05
@jgraham, could provide @whimboo with the Marionette arguments?

**Comment by andreastt** [comment] 2018-08-22 12:58
Yes. You shouldn’t see debug-level output from Marionette by default anymore. You can surface it by passing `--webdriver-arg=-vv` to wptunner, however.

**Comment by foolip** [comment] 2018-08-22 13:16
@Hexcles, can you check a recent run to see if what you originally saw is gone?

**Comment by Hexcles** [comment] 2018-08-22 14:02
Verified (https://travis-ci.org/web-platform-tests/wpt/jobs/419186171#L622). Thanks, @andreastt .

**Comment by foolip** [comment] 2018-08-22 14:03
OK, can't blame https://github.com/web-platform-tests/wpt/pull/11436#issuecomment-415014243 on this issue then :)

**Comment by andreastt** [comment] 2018-08-22 15:00
FWIW we also have a future plan to suppress Firefox output, but it’s a bit into the future: https://bugzilla.mozilla.org/show_bug.cgi?id=1399441

**Comment by whimboo** [comment] 2018-08-23 12:14
I still see TRACE output from Marionette in the latest Travis builds:
https://travis-ci.org/web-platform-tests/wpt/jobs/419595739

So is this really fixed?

**Comment by Hexcles** [comment] 2018-08-23 15:01
Sorry, you're right. The job I was looking at somehow just didn't have trace output.

Travis is currently running geckodriver 0.21.0 & Firefox Nightly. Has the patch not released yet?

**Comment by jgraham** [comment] 2018-08-23 15:06
It looks like the patch still sets `logging::max_level()` as the default level. Am I missing something?

**Comment by whimboo** [comment] 2018-08-23 19:06
Oh, so that was a geckodriver change! So as long as we don't release a new version of geckodriver, nothing might change here, right?

**Comment by Hexcles** [comment] 2018-08-23 20:15
If it's a geckodriver change, then yes. We use the latest released geckodriver, not nightly.

**Comment by foolip** [comment] 2018-08-31 14:35
@whimboo do you know when the next geckodriver release will be?

**Comment by whimboo** [comment] 2018-09-03 08:32
Not shortly. We converted the code from `rustc_serialize` to `serde` which was a big refactoring. So we need a bit more baking time. But would it somehow be possible to run the tests here with a pre-release of geckodriver? It would be great to know that all tests pass too.

**Comment by foolip** [comment] 2018-09-03 08:44
> But would it somehow be possible to run the tests here with a pre-release of geckodriver?

@jgraham? https://github.com/mozilla/geckodriver/releases doesn't have any pre-releases, so I don't know where we'd get them.

**Comment by jgraham** [comment] 2018-09-03 19:04
I mean it's possible, but I don't think it's particularly easy. You get it (iirc) from the `target.common.tests.tar.gz` package, which you an find on `archive.mozilla.org`. Maybe it's possible to convince mozdownload to grab that package and then extract the relevant binary? Otherwise one could probably hardcode the URL.

**Comment by jgraham** [comment] 2018-09-04 12:41
OK, so this was easier than I expected. https://github.com/web-platform-tests/wpt/pull/12824 fixes this, but it depends on https://github.com/web-platform-tests/wpt/pull/12679

**Comment by whimboo** [comment] 2018-09-04 13:03
Do we really want to depend on geckodriver nightly builds? Note that we are not done yet with verification if all the Serde work is fine.

On the other side it would be great to see the real current state of the work I do, and that I don't have to wait until the next geckodriver release to see the changes.

**Comment by jgraham** [comment] 2018-09-04 13:44
geckodriver is only used for wdspec tests and I think that when testing the latest nightly firefox it makes sense to also use the latest nightly geckodriver.

**Comment by whimboo** [comment] 2018-09-04 13:52
Ok, so as long as it is hidden behind the `experimental` filter, it's fine. Thanks.

**Comment by mdittmer** [comment] 2018-09-13 20:08
With  #12824 and #12679 merged, should this be closed @jgraham and @whimboo?

**Comment by whimboo** [comment] 2018-09-13 20:10
If the latest logs don't show the debug and trace output anymore, we can close it.

**Comment by foolip** [comment] 2018-09-24 10:58
https://travis-ci.org/web-platform-tests/wpt/jobs/432302789 is a recent stability run, for https://github.com/web-platform-tests/wpt/pull/13181. It's fairly noisy, but it's not "for every single DOM event and script loading, etc." Treating this as fixed.

**Comment by whimboo** [comment] 2018-09-25 16:22
Yes, that looks fine. We can't prevent the Firefox logs to appear in the logs for now.

**Comment by whimboo** [comment] 2018-09-27 09:20
Well, both the Travis CI and TaskCluster jobs for https://github.com/web-platform-tests/wpt/pull/13232 still show debug and trace output. :(

**Comment by foolip** [comment] 2018-09-27 09:40
That's odd. https://travis-ci.org/web-platform-tests/wpt/jobs/433928918 is a recent job for https://github.com/web-platform-tests/wpt/pull/13235 opened around the same time where the logs weren't as noisy.

@jgraham, who can investigate?

**Comment by whimboo** [comment] 2018-09-27 09:42
Maybe we should check the commands used to start the tests. There might be a difference?

**Comment by jgraham** [comment] 2018-09-27 09:49
I have a vauge memory that @andreastt made the log levels case sensitive? If I'm not totally mistaken about that, I guess we might be passing in the wrong string? (I'm not sure what the argument is for making them case sensitive, but it seems like a dubious idea on the face of it).

**Comment by whimboo** [comment] 2018-09-27 09:52
The level is case-sensitive now but in Marionette we compare it still after running `lowerCase()` on it. So there shouldn't be a problem.

**Comment by whimboo** [comment] 2018-09-27 10:01
I see different invocations of Firefox.

Case 1: No trace / debug output:
https://travis-ci.org/web-platform-tests/wpt/jobs/433928918#L628

> Full command: /home/travis/build/web-platform-tests/wpt/_venv/browsers/nightly/firefox/firefox --marionette about:blank -profile /tmp/tmpGQQV2m.mozrunner

Case 2: trace / debug output:
https://travis-ci.org/web-platform-tests/wpt/jobs/433942495#L914

> Full command: /home/travis/build/web-platform-tests/wpt/_venv/bin/geckodriver --marionette-port 2828 --host 127.0.0.1 --port 4444

So the problem here is that the working case is for non-wdspec tests, while the 2nd case with trace output is for wdspec tests.

**Comment by whimboo** [comment] 2018-09-27 10:14
So what makes us wonder is why there is no debug output for `webdriver::server` from the webdriver crate, but only from Marionette.

**Comment by whimboo** [comment] 2018-09-27 10:34
Ok, so there are two issues here.

First geckodriver incorrectly stores "INFO" instead of "Info" in the `marionette.logging.level` preference. And as such Marionette fails somehow and just prints all debug and trace lines (https://bugzilla.mozilla.org/show_bug.cgi?id=1494611).

We will fix the geckodriver issue immediately because we have to release a new version anyway at latest early next week. Then this issue should be solved. @andreastt will work on that fix.

**Comment by andreastt** [comment] 2018-09-27 11:44
To clarify, we _did_ fix this issue in https://bugzilla.mozilla.org/show_bug.cgi?id=1482829, but it regressed a few days after due to a faulty rebase. We had put in a backwards compatibility fallback in Marionette, but due to another bug this didn’t kick in. See https://bugzilla.mozilla.org/show_bug.cgi?id=1494613#c0 for the full extent of this shitshow.

Sorry about all of this.

**Comment by mdittmer** [comment] 2018-10-04 13:11
@andreastt looks like there's been progress in gecko on this. Has it been fixed? What's the best way to verify?

**Comment by andreastt** [comment] 2018-10-04 13:13
@mdittmer It is fixed in Firefox 64 and you can verify by checking the stdout from geckodriver does not contain any log entries below INFO level.

**Comment by whimboo** [comment] 2018-10-05 06:36
We have released geckodriver 0.23.0 yesterday. So the problem should be fixed now for wdspec tests. @foolip can you have a look if that version of geckodriver is already used?

**Comment by foolip** [comment] 2018-10-05 15:31
I defer to @jgraham. FWIW, it doesn't look like the geckodriver version is pinned in wpt.

**Comment by andreastt** [comment] 2018-10-05 16:03
I believe @jugglinmike or @jgraham fixed it so that the latest version of geckodriver is now always picked up.

**Comment by foolip** [comment] 2018-10-05 17:12
I've filed https://github.com/web-platform-tests/wpt/issues/13399 about the difficulty of determining what geckodriver version is used.

https://taskcluster-artifacts.net/D1rcmB07QXG_T1lClSfh8w/0/public/logs/live_backing.log is still very verbose, but only ~12% of the lines have "Marionette" in them so I'll assume this is now fixed.

**Closed by foolip** 2018-10-05 17:12 UTC
Labels: infra, priority:urgent

**Comment by andreastt** [comment] 2018-10-05 17:19
Thanks for the link to a log. The `INFO` level and above entries we see in this log are to be expected. The log level can be raised to `WARN`, `ERROR`, or `FATAL` if we want to see even less output from geckodriver.

**Comment by foolip** [comment] 2018-10-07 16:13
@andreastt where should we raise the level to `WARN`?  In https://travis-ci.org/web-platform-tests/wpt/jobs/438265534 there is an unreasonable amount of the logging that comes from Marionette.

**Comment by whimboo** [comment] 2018-10-16 08:16
@foolip I don't see that much logging output. So which lines are you referring to?

**Comment by foolip** [comment] 2018-10-16 08:32
@whimboo search for "marionette" in the logs and you see a fair bit of stuff that I'd consider redundant.

**Comment by andreastt** [comment] 2018-10-16 08:42
Probably setting `marionette.log.level` to `Warn` here would do the trick for all non-wdspec test types:
https://searchfox.org/mozilla-central/rev/c9272ef398954288525e37196eada1e5a93d93bf/testing/web-platform/tests/tools/wptrunner/wptrunner/browsers/firefox.py#235-242

**Comment by whimboo** [comment] 2018-10-16 15:28
This looks like a fixed value to me, so a better place is https://searchfox.org/mozilla-central/source/testing/profiles/web-platform/user.js, unless you want to make is configurable via a command line option.
