### ISSUE TITLE
Consistently use one viewport size for reftests

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#7598] opened 2017-10-05 22:57 UTC
We in various places use 800x600 and 600x600 for the reftest screenshot size. We should stop being inconsistent and use one of them everywhere. I think we had agreement to go back to 800x600 after the WPT change to 600x600 for B2G, @jgraham?

https://lists.w3.org/Archives/Public/public-test-infra/2014JanMar/0014.html was the previous discussion about this in 2014.

**Comment by foolip** [comment] 2017-10-09 21:23
Do you have counts for how many tests expect each size currently?

**Comment by gsnedders** [comment] 2017-10-09 21:49
See #5403. Based on that old data set, we have 343 tests that rely on 800x600, and 261 that rely on larger than that. Of those 261, 226 fit in 1600x1200 (the old SPARTAN visual and reftest size), but AFAIK that's not considered overly practical given it makes it hard to run them on plenty of developer's local machines.

**Comment by foolip** [comment] 2017-10-13 15:57
So, if we pick any smaller size, what do we do with tests that don't fit? Rewrite (and accidentally break) those tests?

**Comment by gsnedders** [comment] 2017-10-13 16:05
https://github.com/w3c/web-platform-tests/issues/7135 is one option that was have some limited support for.

**Comment by gsnedders** [comment] 2017-11-24 15:09
I'd like to see this resolved because it makes upstreaming tests from everywhere difficult. WebKit/Blink's LayoutTests use 800x600 viewports and Mozilla's reftests use 800x1000, and as such we can't safely upstream reftests from anywhere without checking their viewport size. (#8150 is an example of a PR partly blocked on having to modify tests to fix in our viewport size.)

**Comment by foolip** [comment] 2017-11-24 15:14
Should we make all tests fail if the viewport size is something unexpected, or how do we do this well?

**Comment by gsnedders** [comment] 2017-11-24 16:21
@foolip IIRC, there was some desire to be able to use reftests to test things involving scrollbars, but I don't think that actually works with WebDriver today. @jgraham?

**Comment by foolip** [comment] 2017-11-24 17:20
Ignore me, here I was thinking this was the similar issue about testharness.js, for reftests there's not really a problem.

Except, perhaps... will this work at all for mobile testing, where the screen might not be 800 of wide?

**Comment by gsnedders** [comment] 2017-11-28 16:03
@foolip The screen might not be 600 pixels wide on mobile, too, though (e.g., the Galaxy J2 and Moto C both from 2017, with 540x960 and 480x854 screens respectively). Maybe that's paranoia, but mobile testing is hard (unless we allow for different layout and visual viewports, in which case we can render almost any size of layout viewport fine).

**Comment by jgraham** [comment] 2017-11-28 16:17
I don't think that scrollbars will necessarily be included in the screenshot, but I think the screenshot is supposed to be the visual viewport, not the full document, so it should in theory work. I don't know if chromedriver actually does that right or not.

I seem to remember saying somewhere else that if we think that >600x600 is acceptable we should choose 800x1000 because most tests that work in 800x600 will also work in 800x1000, but the reverse isn't true.

Whatever we do I expect some tests to break here.

**Comment by jgraham** [comment] 2017-11-28 16:24
On a high-end phone, it's unclear to me if it's possible to set things up so that one device pixel equals one physical pixel, without which a) the screens are often too small anyway and b) the tests will have many spurious failures because hidpi isn't well supported by existing reftests.

Honestly the best way of testing mobile browsers might be via emulators, which mean that the available resolutions are close to desktop. I think Mozilla do all of the platform-level mobile testing in emulators these days. Maybe that doesn't work for iOS, but I'm inclined not to care so much about single-browser-engine platforms.

**Comment by foolip** [comment] 2018-01-25 13:23
This is in the list of issues for [Resolve known important infra issues for wpt](https://docs.google.com/document/d/1ojlLDiRruI4e95Z7JQ10JQPRMiQHd_40rBkYCL6IJqw/edit#heading=h.khrf1xe3i7e5).

@gsnedders, maybe we can limit this issue to just cases where https://w3c.github.io/webdriver/webdriver-spec.html#set-window-rect actually works, and punt on the mobile browser problem? I basically don't think we can solve that and still be able to test on real mobile phones and real browsers, which I think we'll want to do for wpt.fyi, so maybe we'll just have to live with that.

**Comment by alijuma** [comment] 2018-04-03 13:44
This has priority:roadmap. Is there any work planned here this quarter?

**Comment by foolip** [comment] 2018-05-09 14:07
@gsnedders and I discussed this today. Next step is probably to try run all reftests in Chrome and Firefox with the current default size 600x600 and with 800x600, and list any tests where the results changed. If there are only a handful, then maybe sticking with 600x600 will be fine, and otherwise we'll see. So work is still planned this quarter.

**Comment by gsnedders** [comment] 2018-05-10 16:39
@foolip My big concern isn't where the result is changed currently, but say we have some test that currently passes, but then we regress something in the bottom right (outside of the viewport) and we don't catch it.

**Comment by foolip** [comment] 2018-05-10 17:53
Overall, would you guess that regressions are more likely to be caught at 600x600 or 800x600, if they originally pass at both resolutions? Seems this depends on what size they were authored for, and can we know/guess that?

**Comment by gsnedders** [comment] 2018-05-11 12:44
@foolip I think the majority of tests we have were authored for either 800x600 (which I believe is what happens with content_shell in WebKit/Blink) or 800x1000 (in the old Gecko reftest infra). So I'd guess 800x600 is a better bet than 600x600.

**Comment by foolip** [comment] 2018-05-15 08:26
I've confirmed that 800x600 is the size in Blink's LayoutTests, ~99% of the 27k *-expected.png files have that size, 100+ are 1600x1200 because of scaling, and then there's a mix of other sizes because of use of `testRunner.dumpDragImage()`, some SVG test, etc.

So 800x600 would be a handy default in WPT for us.

@jgraham, do you have a way to check how many of Gecko's tests would change their results if the size were decreased to 800x600? I guess the hard case is where they pass before and after, but after they no longer work as regression tests. Not even checking how much of the screenshot is non-white ought to eliminate this problem...

**Comment by gsnedders** [comment] 2018-05-15 13:05
@foolip https://bugzilla.mozilla.org/show_bug.cgi?id=1128211 is open on making the old Gecko reftest harness use something smaller.

**Comment by foolip** [comment] 2018-07-18 09:00
This issue came up in triage today, and I think it still is fairly high priority, so included it explicitly in ecosystem infra's Q3 [known important infra issues](https://docs.google.com/document/d/1uh7A24pT6P70Lb9CeFCKga3RrrdzLK7tSAR7o8C7No0/edit#heading=h.3sszqdrf0hk7).

**Comment by gsnedders** [comment] 2018-08-16 15:54
https://treeherder.mozilla.org/#/jobs?repo=try&revision=7beaecd8c9c3e14b0531bfb4d57abb05cd1f83b7 is a try job with Gecko using 800x600 for WPT.

**Comment by gsnedders** [comment] 2018-08-16 16:10
@foolip:

> do you have a way to check how many of Gecko's tests would change their results if the size were decreased to 800x600? I guess the hard case is where they pass before and after, but after they no longer work as regression tests. Not even checking how much of the screenshot is non-white ought to eliminate this problem...

Making reftests *smaller* is a much harder problem than making them larger (very few break when you expand the size of the viewport).

My gut is there's plenty of them and it's probably not worth the time to triage all of them.

I still suspect the easiest thing to do is to add support for `<meta name=viewport>` to configure the viewport size so those that rely on larger viewports can just be made to work? (Of course, it's unlikely indefinitely large viewports will work, but we can probably go bigger than 800x600!)

> maybe we can limit this issue to just cases where https://w3c.github.io/webdriver/webdriver-spec.html#set-window-rect actually works, and punt on the mobile browser problem? I basically don't think we can solve that and still be able to test on real mobile phones and real browsers, which I think we'll want to do for wpt.fyi, so maybe we'll just have to live with that.

One option is to just say that the resolution is *at least* 800x600 and make it valid to run them on larger sizes (there's very, very few that break currently as a result of this, AFAIK). This does of course rely on the mobile browser having a layout viewport of at least 800x600 (or visual viewport, depending on what we take the screenshot of!).

**Comment by foolip** [comment] 2018-08-16 20:56
> Making reftests *smaller* is a much harder problem than making them larger (very few break when you expand the size of the viewport).
> 
> My gut is there's plenty of them and it's probably not worth the time to triage all of them.

Yeah, let's not go looking for more trouble than we already have.

> I still suspect the easiest thing to do is to add support for `<meta name=viewport>` to configure the viewport size so those that rely on larger viewports can just be made to work? (Of course, it's unlikely indefinitely large viewports will work, but we can probably go bigger than 800x600!)

Using `<meta name=viewport>` specifically is probably a bad idea since it'll also influence the browser behavior, not just the size set by the runner. Anyhow, can we separate this from changing the default, right, or do you think this change will break some tests that have to be fixed by such a mechanism?

> One option is to just say that the resolution is *at least* 800x600 and make it valid to run them on larger sizes (there's very, very few that break currently as a result of this, AFAIK). This does of course rely on the mobile browser having a layout viewport of at least 800x600 (or visual viewport, depending on what we take the screenshot of!).

That might work, at least one some tablets. But let's ignore this problem until we're trying to run on a platform where resizing the browser isn't possible.

**Comment by gsnedders** [comment] 2018-08-18 11:01
> Using `<meta name=viewport>` specifically is probably a bad idea since it'll also influence the browser behavior, not just the size set by the runner.

True. 🙂 We can certainly use some other name!

> Anyhow, can we separate this from changing the default, right, or do you think this change will break some tests that have to be fixed by such a mechanism?

If we're just changing it to 800x600, I think we should just do it. Need to triage all the differences from the above run though.

**Comment by foolip** [comment] 2018-08-19 20:30
Yep, just change the default for now. Once the Firefox differences are triaged it might be interesting to also see if there are differences in Chrome, but ultimately it doesn't matter as much since we're already using 800x600 in content_shell.

**Comment by gsnedders** [comment] 2018-08-20 21:07
Related: #12578. We should probably fix that at the same time.

**Comment by gsnedders** [comment] 2018-08-27 14:34
So having looked through the Firefox changes, I think that moving to 800x600 doesn't break anything?

**Comment by foolip** [comment] 2018-08-27 16:02
Are there no changes at all, not even tests that began passing as a result? It's suspicious if no differences at all can be spotted.

**Comment by gsnedders** [comment] 2018-08-27 16:03
There are changes (quite a lot), but almost all are unexpected passes, all of which seem correct. The single unexpected failure is caused by the test not correctly failing on a narrow viewport.

**Comment by gsnedders** [comment] 2018-08-27 16:27
We should also make sure everyone is on-board with changing the reftest size before we land any change here.

**Comment by jugglinmike** [comment] 2018-08-27 20:41
The only problems I can imagine would come if this change were somehow incompatible with `xvfb` or if they necessitated a change to the invocation of `wpt run`. I don't think either of these are true, though, so we should be good.

**Comment by jugglinmike** [comment] 2018-08-28 17:14
The [results-collection project uses `xvfb-run`](https://github.com/web-platform-tests/results-collection/blob/a239e9a12c662b27ca8d89d4df21e103df0608d6/src/master/wpt_run_step.py#L77), and  [`xvfb-run`](http://manpages.ubuntu.com/manpages/xenial/man1/xvfb-run.1.html) wraps [`xvfb`](https://linux.die.net/man/1/xvfb). We don't specify any arguments via `--server-args`, so the `-screen` option takes the default value of `1280x1024x8`. So for the locally-run browsers, any of the dimensions mentioned in this thread should be acceptable.

I just realized that none of the above applies to the proprietary browsers, though. That's because we currently run them on their native operating systems via Sauce Labs. Currently, [the WPT CLI doesn't specify a desired screen resolution](https://github.com/web-platform-tests/wpt/blob/f23bb9e37fdf694021519b0e7ce2c282fa026ea5/tools/wptrunner/wptrunner/browsers/sauce.py#L38-L72), and [the Sauce Labs documentation doesn't specify the default value](https://wiki.saucelabs.com/display/DOCS/Test+Configuration+Options?preview=%2F48365728%2F63476108%2FSauce+Labs+Test+Configuration+Options.pdf).  I've contacted the support staff for clarification, but judging from [their "platform configurator" page](https://wiki.saucelabs.com/display/DOCS/Platform+Configurator#/), we ought to be able to specify a resolution that is large enough to support any of the window sizes mentioned so far.

I'll share the information from Sauce Labs here since it will determine whether this feature needs to also include a change to wptrunner's use of Sauce Labs.

**Comment by jugglinmike** [comment] 2018-08-31 00:34
Sauce Labs support got back to me, and we now have docs!

> Default screen resolution for Sauce tests when not specified is 1024x768.

So if we go with @jgraham's [suggestion to use 800x1000](https://github.com/web-platform-tests/wpt/issues/7598#issuecomment-347576216), then we'll need to update wptrunner. Otherwise, no change is necessary.

**Comment by foolip** [comment] 2018-08-31 07:57
https://github.com/web-platform-tests/wpt/pull/12695 is going with 800x600, in which case no impact for Sauce.

**Comment by jgraham** [comment] 2018-08-31 10:06
@dbaron Do you have any objection to making wpt reftets 800x600 rather than 600x600? Based on the gecko run mentioned about it looks like authors are writing tests incorrectly assuming a larger viewport so there are a bunch of spurious failures from running at 600x600 (it's unclear where this converges i.e. we might get even more passes running at a larger size).

**Comment by gsnedders** [comment] 2018-08-31 11:30
@jgraham @dbaron IIRC, it converges near Presto's old 1600x1200, which I think is too large to be practical.

**Comment by gsnedders** [comment] 2018-09-12 23:18
@dbaron did you see https://github.com/web-platform-tests/wpt/issues/7598#issuecomment-417618025?

**Comment by foolip** [comment] 2018-11-13 09:32
@gsnedders, do you have an update on this? When do we change the viewport size?

**Comment by gsnedders** [comment] 2018-11-28 17:51
@foolip https://bugzilla.mozilla.org/show_bug.cgi?id=1510696 is the bug on the Firefox side to avoid hardcoding the reftest size in Marionette for the internal reftest runner, which now has a patch which on the face of it works.

Apart from that, we have two choices: disable the internal reftest runner for older versions of Firefox (prior to whenever that lands), or wait until that reaches stable (we don't need to care about ESR, do we?).

Also still want feedback from other vendors, and those maintaining legacy reftest systems.

**Comment by jgraham** [comment] 2018-11-28 17:55
I am working on android reftests and vertical overflow is a huge problem :( Any test that overflows the viewport is unstable because the scrollbars sometimes appear in the screenshots.

**Comment by foolip** [comment] 2018-11-29 14:01
> disable the internal reftest runner for older versions of Firefox (prior to whenever that lands), or wait until that reaches stable

Those aren't great options :( After verifying that it will work, I guess I'd have to vote for waiting until the changes reaches stable.

**Comment by gsnedders** [comment] 2019-01-10 17:31
> https://bugzilla.mozilla.org/show_bug.cgi?id=1510696 is the bug on the Firefox side to avoid hardcoding the reftest size in Marionette for the internal reftest runner, which now has a patch which on the face of it works.

After spending way too long chasing down Win7-only failures (which turned out to be leaking memory, and the lower memory limit of Win7 32-bit causing only that platform to hit OOM), it should now land shortly. Then all we need to do is wait for the it to ride the release train…

**Comment by gsnedders** [comment] 2019-01-14 23:35
This appears to have finally landed and stayed landed. Presumably will reach stable with Firefox 66, on 2019-03-19.

**Comment by foolip** [comment] 2019-01-15 10:19
Can the changes in wpt be developed against Firefox Nightly / Dev / Beta so that we can land them on 2019-03-19?

**Comment by gsnedders** [comment] 2019-01-15 10:35
@foolip yes

**Comment by jgraham** [comment] 2019-01-15 10:54
You can land them earlier, it just means that Firefox stable will have incorrect results for a while (we *could* uplift the patch, but I don't think that it's worthwhile).

**Comment by foolip** [comment] 2019-01-15 11:04
Would that look like a lot of regressions on Firefox stable, or that it's precisely the current results modulo flakiness?

BTW, what does the code look like for ensuring that the content size is 800x600 as opposed to the window size? That was pretty unsightly in some WebDriver code I wrote as a test.

**Comment by jgraham** [comment] 2019-01-15 11:14
It looks like the current results, although it would look like a lot of fixes (and maybe some regressions) in nightly if more tests work at the larger size.

It seems we didn't fix things to set the right viewport size yet [1]? Which is surprising to me because I remember seeing a fix here. @gsnedders will know what's going on.

[1] https://github.com/web-platform-tests/wpt/blob/f6c42824add97dac84434c92c606aacd867c3534/tools/wptrunner/wptrunner/executors/executorwebdriver.py#L406

**Comment by gsnedders** [comment] 2019-01-15 17:07
@jgraham we didn't land #12695.

**Comment by jgraham** [comment] 2019-01-15 17:38
I think we should land this asap. Although Firefox stable runs won't pick up the change for a couple of months it will make the results more correct on every other configuration, and developers almost universally care about the results in nightly rather than stable, so I'm confident that the discrepancy between Firefox stable and other browsers won't be a substantial problem.

**Comment by jgraham** [comment] 2019-01-17 10:38
I stil lthink we shouldn't consider this blocked on marionette changes reaching stable. That is I'm happy with the ordering, but should land this as soon as we are sure that the other change will stick.

**Comment by foolip** [comment] 2019-02-13 10:45
Landing the change before it works in Firefox stable seems fine to me, especially that @jgraham supports it.

**Comment by gsnedders** [comment] 2019-02-13 10:55
It's also on beta now, so we should probably just go ahead and land it.

**Comment by gsnedders** [comment] 2019-02-13 10:55
Especially now wpt.fyi shows experimental by default.

**Comment by foolip** [comment] 2019-02-15 12:55
Let's do it!

**Closed** 2019-02-18 15:52 UTC
Labels: docs, infra, priority:roadmap, wptrunner
